### ISSUE TITLE
Limit subtitle length

### ISSUE THREAD

**Issue by KevinGeLe** [m-bain/whisperX#100]
Is there away to limit the sentence length, so that they dont fill the entire screen. The way that others have said to do is if the sentence is more than a specified character length. It shall just cut it and add it to a new subtitle, but the timestamps is wrecked doing that and it also doesnt cut it where it is supposed to eg. Names, places, but, if etc.

**Comment by chenlung** [comment]
This might help: [Netflix English Timed Text Style Guide](https://partnerhelp.netflixstudios.com/hc/en-us/articles/217350977-English-Timed-Text-Style-Guide#h_c0a8cf1c-089b-4b6f-94e3-fbb4d03faa2a).

**Comment by m-bain** [comment]
supported in v3 https://github.com/m-bain/whisperX/tree/v3

https://github.com/m-bain/whisperX/issues/200#issuecomment-1528966841
