### ISSUE TITLE
Add a feature that uses existing subtitle or text to force alignment instead of transcribed

### ISSUE THREAD

**Issue by ilai11** [m-bain/whisperX#101]
This function is required in two cases：
1. I want shorter subtitles per line，Whisperx transcribes many long subtitles. I want to split myself and then align.
2. I have the correct text. After I manually divide the text into lines, I need to synchronize each line with the audio.Then I can get an almost perfect subtitle.
There are other alignment methods, but not as accurate as whiperx.
It would be great if this function could be added, thanks！

**Comment by aeciorc** [comment]
+1

**Comment by thomascour** [comment]
+1

**Comment by mayeaux** [comment]
> This function is required in two cases：
> 
> 1. I want shorter subtitles per line，Whisperx transcribes many long subtitles. I want to split myself and then align.
> 2. I have the correct text. After I manually divide the text into lines, I need to synchronize each line with the audio.Then I can get an almost perfect subtitle.
>    There are other alignment methods, but not as accurate as whiperx.
>    It would be great if this function could be added, thanks！

What other options are there for aligning existing subtitles with the media? Considering you can use `--no_align` I expect t his to be possible though I haven't dug into the WhisperX code yet

**Comment by m-bain** [comment]
https://github.com/m-bain/whisperX/issues/36#issuecomment-1399223227
