### ISSUE TITLE
Timestamp problems on non-English samples

### ISSUE THREAD

**Issue by olevanss** [m-bain/whisperX#106]
Hi there!

I tried to use whisper_timestamped for better time stamping. My test samples are the premade voice lines recorded in one .wav file separated by 2 seconds. For me it looked like it should be an easy task for a Whisper. After it failed I moved to whisperX and other whisper timestamping method.

I attach some interesting results I got. The blue graph is the waveform of my audio, while red ranges are the timelines provided by whisperX.

![whisperX_sample3](https://user-images.githubusercontent.com/86475004/222055360-d211ab55-4737-4957-ac65-3c1decc65000.png)

![whisperX_sample2](https://user-images.githubusercontent.com/86475004/222055347-4efae9d0-8733-4d39-8ba7-29932cd3d964.png)

![whisperX_sample1](https://user-images.githubusercontent.com/86475004/222055289-e0fbcd0b-f326-4f22-a0c9-756472b5a2bf.png)

Most frequent errors I get are:

1. Whisper_timestamped ignores phrases in timestamping
2. It puts wrong timestamps onto them.
or
3. Attached silent periods bordering the phrase to the phrase timestamps.
4. 
So, while overall performance is good, I would like to ask if I can do something to improve performance. I tried varying interpolation model, extend duration and importing non-default wav2vec models of my language. It seems to have little effect.

**Comment by m-bain** [comment]
which language is this?
