### ISSUE TITLE
[QOL Request] m4a support with VAD

### ISSUE THREAD

**Issue by Infinitay** [m-bain/whisperX#108]
From basic testing it seems like m4a is currently unsupported when using VAD. mp3 too for that matter (#41) but updating `soundfile` to v0.11.0 and by association `libsndfile` to v1.1.0 I was able to use whisperx with mp3s. However, as stated earlier m4a's are still unsupported when used alongside VAD. It would be a nice feature to be able to convert an unsupported audio or video file to a supported audio format to be used with whisperx and pyannote. Instead of having to pre-process the files ourselves and storing multiple versions of the file to be processed or removing the original to have a supported format for whisperx, would it be possible to convert it to an appropriate format and passing its data instead using something like ffmpeg-python?

**Comment by m-bain** [comment]
fixed now with torchaudio.load I believe
