### ISSUE TITLE
Updating soundfile version caused conflict on pyannote.audio 

### ISSUE THREAD

**Issue by cnbeining** [m-bain/whisperX#118]
In PR #111 `soundfile` is version locked to `>=0.12.0` to fix MP3 import issue.

However `pyannote.audio` has `soundfile` locked to `>=0.10.2,<0.12` per https://github.com/pyannote/pyannote-audio/blob/develop/requirements.txt#L17 .

This conflict shall cause PIP to go for the last version of `pyannote.audio` without conflict which is version 1.1.2(!!!) as per https://github.com/pyannote/pyannote-audio/blob/c5de4f2f7e3a47dfbc6c4644af409a43ff22a09c/requirements.txt#L12 .

Fixes proposed:

- Very short term: Install WhisperX, and force upgrade `pyannote.audio` with `pip install pyannote.audio -U` to bring `pyannote.audio` to version 2.1.1.
- Short term: revert PR #111 for now.
- Longer term: We should reach out to upstream and see why they are doing this specific version locking.

Cheers,

**Comment by cnbeining** [comment]
@Barabazs FYI :-(

**Comment by cnbeining** [comment]
Reached out to upstream for clarification on version locking `soundfile`.

**Comment by koldbrandt** [comment]
I am experiencing the same thing. Just downgraded soundfile and it works. Maybe just remove soundfile from the requirements file and let pyannote install whatever version that they have in their requirements file.

**Comment by cnbeining** [comment]
In that case WhisperX will lost MP3 processing capacity - I am gonna communication with upstream for resolution. Sent from my iPhoneOn Mar 5, 2023, at 7:24 AM, Marcus Brandt ***@***.***> wrote:﻿
I am experiencing the same thing. Just downgraded soundfile and it works. Maybe just remove soundfile from the requirements file and let pyannote install whatever version that they have in their requirements file.

**Comment by koldbrandt** [comment]
Yeah you are completely right that it is losing the mp3 capabilities. I am trying to find a fix for that right now. The most easy fix that I have found is to fork pyannote and then make it so I can call the pipeline with numpy array of samples and sample rate, and then use whispers loading function, which is reliant on ffmpeg. 
If you find a solution with upstream, then please let me know

**Comment by koldbrandt** [comment]
So I have a fix for this. It may not be pretty, but it works. 
When calling the vad pipeline, instead of calling with the file name, then you can call it with a mapping. I loaded the audio with whispers load function. This is mono and when you do a mapping, then it has to be stereo. This can be modeled as just this mono channel in 2 channels. 

wave= whisperx.load(audio)
wave= torch.tensor((wave,wave))
vad_pipeline({"waveform": wave, "sample_rate": SAMPLE_RATE})

This gives us the possibility to load all audio files that are supported by ffmpeg

**Comment by Barabazs** [comment]
My workaround is:
1. install whisperx as usual
2. `pip install "soundfile>=0.12.0" --upgrade`

I don't have any issues with this workaround.

**Comment by Barabazs** [comment]
The conflict doesn't seems resolved now. Closing as obsolete.
