### ISSUE TITLE
Use of fine-tuned Whisper

### ISSUE THREAD

**Issue by PeterGilles** [m-bain/whisperX#12]
What a great tool! Is it somehow possible to use also a version of Whisper that has been fine-tuned? I have one model trained with transformers on Hugging Face.
Thanks.

**Comment by m-bain** [comment]
It's possible. See python example here.
https://github.com/m-bain/whisperX#python-usage-

"results" can instead come from your custom huggingface whisper. Just check it's in the same format.

**Comment by Jasper750** [comment]
hello I use your script under python why once finished it does not create any srt file?

**Comment by m-bain** [comment]
@Jasper750 please read the code, there is utils.write_srt
