### ISSUE TITLE
Adds support for FasterWhisper

### ISSUE THREAD

**Issue by playdasegunda** [m-bain/whisperX#121]
A suggestion would be to add support for [Faster Whisper](https://github.com/guillaumekln/faster-whisper/), which is much faster and uses much less VRAM than Whisper. You can use the Whisper Large V2 model and only use [4.6GB VRAM](https://github.com/guillaumekln/faster-whisper/#large-model-on-gpu) instead of the original 10GB. If you can add this, it will be very useful for the community.

**Comment by Infinitay** [comment]
This is great. I'd love to have this paired in addition to our batch processing for even faster speeds. Does it have any impact on transcription accuracy?

**Comment by arnavmehta7** [comment]
Alright, I researched. Seems like the decoding way, tokenizer of whisper, faster-whisper, and whisperx are quite different.

**Comment by Barabazs** [comment]
Closing because it's already implemented.
