### ISSUE TITLE
Error loading model from HF when running on Google Colab but no problem running locally? 

### ISSUE THREAD

**Issue by ifeimi** [m-bain/whisperX#124]
Hi, I'm trying to get whisperX running in a Jupyter Notebook on Google Colab ([Here it is](https://github.com/ifeimi/Whisper48/blob/main/FeimiWhisperx_debug.ipynb)). On my PC it runs perfectly with no error, but if I run the almost exact same script on Google Colab (the only difference is now I load an audio file from Google Drive of course), I keep getting this "Error loading model from HF" during the process of loading align model. 

The code I was using was:
```
device = "cuda"
torch.cuda.empty_cache()
print('加载whisper模型 Loading whisper model...')
model = whisperx.load_model(model_size, device)

#Original whisper transcribe
tic = time.time()
print('识别中 Transcribe in progress...')
result = model.transcribe(audio_file, language =language)

#Load alignment model and metadata
print('加载调整模型 Load alignment model...')
#model_name = "jonatasgrosman/wav2vec2-large-xlsr-53-japanese"
model_a, metadata = whisperx.load_align_model(language_code="ja", device=device) # error happened here

#Align whisper output
print('调整识别结果 Align whisper output...')
result_aligned = whisperx.align(result["segments"], model_a, metadata, audio_file, device)
```

The output was as follow:

```

> 加载whisper模型 Loading whisper model...
> 100%|████████████████████████████████████████| 461M/461M [00:04<00:00, 120MiB/s]
> 识别中 Transcribe in progress...
> 加载调整模型 Load alignment model...
> Downloading (…)rocessor_config.json: 100%
> 158/158 [00:00<00:00, 6.38kB/s]
> Expecting value: line 1 column 1 (char 0)
> Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models
> ---------------------------------------------------------------------------
> JSONDecodeError                           Traceback (most recent call last)
> [/usr/local/lib/python3.8/dist-packages/whisperx/alignment.py](https://localhost:8080/#) in load_align_model(language_code, device, model_name)
>      62         try:
> ---> 63             processor = Wav2Vec2Processor.from_pretrained(model_name)
>      64             align_model = Wav2Vec2ForCTC.from_pretrained(model_name)
> 
> 17 frames
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> [/usr/local/lib/python3.8/dist-packages/whisperx/alignment.py](https://localhost:8080/#) in load_align_model(language_code, device, model_name)
>      66             print(e)
>      67             print(f"Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models")
> ---> 68             raise ValueError(f'The chosen align_model "{model_name}" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)')
>      69         pipeline_type = "huggingface"
>      70         align_model = align_model.to(device)
> 
> ValueError: The chosen align_model "jonatasgrosman/wav2vec2-large-xlsr-53-japanese" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)

```

The language I'm using is Japanese. It looks like the program cannot find the correct align_model on HuggingFace, but the model is obviously [existing](https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-japanese). And again, I had no problem running it locally with Jupyter Notebook. 

So I wonder if this could be some communication error between Google Colab and HuggingFace? 

Finally, what was even weirder is, at some point tonight, I was able to get the program working on Google Colab. But 30 minutes later when I ran the SAME script again, it just failed, like what I described above (what the fuck?). 

This is my first time submitting an issue on GitHub, sorry if any of my descriptions are inaccurate. Thank you very much in advance for any suggestions.

**Comment by ifeimi** [comment]
Changed the link to my notebook so that I can make modifications to the original repository.

**Comment by cnbeining** [comment]
You may want to refer to https://github.com/cnbeining/Whisper_Notebook/blob/master/WhisperX.ipynb .

This notebook has been serving [ACICFG](https://chineseaci.com/) for this season: opinionated with our standard and optimized for English but workflow should be transferable in your case.

Email me on GitHub contact if you wanna discuss about Fansub :-)

**Comment by ifeimi** [comment]
> You may want to refer to https://github.com/cnbeining/Whisper_Notebook/blob/master/WhisperX.ipynb .
> 
> This notebook has been serving [ACICFG](https://chineseaci.com/) for this season: opinionated with our standard and optimized for English but workflow should be transferable in your case.
> 
> Email me on GitHub contact if you wanna discuss about Fansub :-)

@cnbeining Hi, thank you so much for your very kind advice! I finally got some time to look at this issue again this week, and it seems that the problem has somehow been fixed (magically). Now the script should work just fine (I published it on my github already). As I suspected before, it could be a temporal communication problem.
