### ISSUE TITLE
Feature request: Customise the words per line?

### ISSUE THREAD

**Issue by umaar** [m-bain/whisperX#127]
Thanks for this project, it works so well. Was wondering if you'd consider adding support for a CLI flag that lets you specify how many words per line, while still highlighting the current word. For example, I see whisperX produces a file that has line like this:

```
Dialogue: 0,0:00:27.82,0:00:27.94,Default,,0,0,0,,down {\1c&HFF00&\u1}for{\r} us.
```

Which is great! But could also be nice to customise how many words, in total, are displayed per line - while preserving the behavior of the current word highlighting.

**Comment by Barabazs** [comment]
Implemented with `--max_line_width`
