### ISSUE TITLE
use whispxerx to split up audio files?

### ISSUE THREAD

**Issue by silvacarl2** [m-bain/whisperX#134]
hi, is it possible/feasible, to use whipserx to split up audio files so each file would contain unique recorded words?

we are looking at doing this to create a corpus of spoken first and last names.

carl

**Comment by eyespywmlileye** [comment]
Hi Carl , yes it is possible , what you could try to do it use WhisperX to collect world-level time stamps.

From there you could use the time stamps as start time and end time , then use those 2 time stamps to extract individual words and save those files as new audio files. 

If you need more clarity , you can message me

**Comment by silvacarl2** [comment]
THIS IS CRAZY COOL.

yes, i will give it a try and let you know how it works.

**Comment by silvacarl2** [comment]
so just to cliarfy, when i get this:

1
00:00:00,483 --> 00:00:01,066
Hayley

2
00:00:01,388 --> 00:00:01,891
Andrews.

i can use this to cut the audio from 483 to 1.66 to get just the word "Hayley" and from 1.388 to 1.891 to get just the word "Andrews", correct?

sample file: https://www.dropbox.com/s/4h0cydcyprcqe22/101018-Hayley-Andrews.mp3?dl=0

**Comment by silvacarl2** [comment]
question: using this with fastAPI behaves the same as vanilla whisper?  Any API thing we need to check out?

**Comment by eyespywmlileye** [comment]
> so just to cliarfy, when i get this:
> 
> 1 00:00:00,483 --> 00:00:01,066 Hayley
> 
> 2 00:00:01,388 --> 00:00:01,891 Andrews.
> 
> i can use this to cut the audio from 483 to 1.66 to get just the word "Hayley" and from 1.388 to 1.891 to get just the word "Andrews", correct?
> 
> sample file: https://www.dropbox.com/s/4h0cydcyprcqe22/101018-Hayley-Andrews.mp3?dl=0

Yea, exactly that, 

I wrote an algorithm that I think you can optimise, but it should work regardless. 

Do you have a sample audio I could implement the algorithm on? The current dropbox is empty. 

 I'll share a jupyter notebook with the implementation.

**Comment by silvacarl2** [comment]
sprry, hang on.

**Comment by eyespywmlileye** [comment]
> the idea being we have 11M samples and we want to create a corpus of names reognition plus publish it for other people to use.

So if I am understanding you correctly, you want to use Named Entity Recognition to identify names from text and then extract those names and the timestamps in which they are uttered?

**Comment by eyespywmlileye** [comment]
> question: using this with fastAPI behaves the same as vanilla whisper? Any API thing we need to check out?
> 
> p.s. is it my imagination or is this implementation more accurate than whisper vanilla?

Yea using it with  fast API/ Flask does behave the same 
This implementation is definitely much more accurate! and the fact that it has word-level timestamps adds much more utility.

**Comment by eyespywmlileye** [comment]
> sorry, use this zip: https://www.dropbox.com/s/yu8u9auxvixtpr9/tough-names-to-recognize.zip?dl=0
> 
> these are 3 samples whipser vanilla has a tough time with.

I'll have a go at it and get back to you in 24hrs

**Comment by silvacarl2** [comment]
> So if I am understanding you correctly, you want to use Named Entity Recognition to identify names from text and then 
> extract those names and the timestamps in which they are uttered?

yes.  its for patient chart lookup, we have 11M samples to test with and train on.  its beyond normal NER because it is entirely speech to text based.  i could go on and on about this but trust me, its painful.

we are doing the same for date of birth as well.

>Yea using it with fast API/ Flask does behave the same

so:

mel = whisper.log_mel_spectrogram(audio).to(model.device)

becomes:

mel = whisperx.log_mel_spectrogram(audio).to(model.device)

is this accurate?

This implementation is definitely much more accurate! and the fact that it has word-level timestamps adds much more utility.

**Comment by silvacarl2** [comment]
yes

**Comment by m-bain** [comment]
This is a cool idea, if you are compute limited please DM me since I have not pushed the 70x real time code. It's using a custom Huggingface fork of mine. And can help if you need to run at scale

**Comment by silvacarl2** [comment]
we can lend you any size hosted system you want to test your ideas.

**Comment by silvacarl2** [comment]
Push it?  8-)858-703-7309On Mar 13, 2023, at 4:22 PM, m-bain ***@***.***> wrote:﻿
This is a cool idea, if you are compute limited please DM me since I have not pushed the 70x real time code. It's using a custom Huggingface fork of mine. And can help if you need to run at scale

**Comment by eyespywmlileye** [comment]
> This is a cool idea, if you are compute limited please DM me since I have not pushed the 70x real time code. It's using a custom Huggingface fork of mine. And can help if you need to run at scale

Cool, I'll definitely you know when we need extra compute !

**Comment by eyespywmlileye** [comment]
> we can lend you any size hosted system you want to test your ideas.
> 
> yes, at a minimum we are handling 450,000 patient calls a month.
> 
> the idea is to take the best possible speech to text and then using a fine tuned GPT-J model get it right as close to 100% of the time as possible.
> 
> by get it right i mean get the first and kast name of the patient and their date of birth as close to 100% correct as possible, 450,000 times to start a month.
> 
> just emailed you as well.

Hi, please check your email. 
Here is the link to the google_colab notebook of the basic implementation , given the audio files: https://colab.research.google.com/drive/1iGjf0OXfUk-5CQ0h_vgeqpy-6MNO2NYb?usp=sharing

**Comment by silvacarl2** [comment]
push out the 70x real time code, its always a good idea to test all options!  ok?  8-)

**Comment by silvacarl2** [comment]
> > we can lend you any size hosted system you want to test your ideas.
> > yes, at a minimum we are handling 450,000 patient calls a month.
> > the idea is to take the best possible speech to text and then using a fine tuned GPT-J model get it right as close to 100% of the time as possible.
> > by get it right i mean get the first and kast name of the patient and their date of birth as close to 100% correct as possible, 450,000 times to start a month.
> > just emailed you as well.
> 
> Hi, please check your email. Here is the link to the google_colab notebook of the basic implementation , given the audio files: https://colab.research.google.com/drive/1iGjf0OXfUk-5CQ0h_vgeqpy-6MNO2NYb?usp=sharing

need access to this notebook.  8-)

**Comment by eyespywmlileye** [comment]
try it now 

> > > we can lend you any size hosted system you want to test your ideas.
> > > yes, at a minimum we are handling 450,000 patient calls a month.
> > > the idea is to take the best possible speech to text and then using a fine tuned GPT-J model get it right as close to 100% of the time as possible.
> > > by get it right i mean get the first and kast name of the patient and their date of birth as close to 100% correct as possible, 450,000 times to start a month.
> > > just emailed you as well.
> > 
> > 
> > Hi, please check your email. Here is the link to the google_colab notebook of the basic implementation , given the audio files: https://colab.research.google.com/drive/1iGjf0OXfUk-5CQ0h_vgeqpy-6MNO2NYb?usp=sharing
> 
> need access to this notebook. 8-) its not set to shareable.

try it now ?

**Comment by silvacarl2** [comment]
I am.  8-)

**Comment by silvacarl2** [comment]
> > question: using this with fastAPI behaves the same as vanilla whisper? Any API thing we need to check out?
> > p.s. is it my imagination or is this implementation more accurate than whisper vanilla?
> 
> Yea using it with fast API/ Flask does behave the same This implementation is definitely much more accurate! and the fact that it has word-level timestamps adds much more utility.

question, are end points the same such as:

mel = whisper.log_mel_spectrogram(audio).to(model.device)

would be:

mel = whisperx.log_mel_spectrogram(audio).to(model.device)?

**Comment by silvacarl2** [comment]
got this at the very bottom of the notebook, checking out why now:

RuntimeError: Error opening '/content/output/123764-Cheryl-Cross_0.wav': System error.

**Comment by eyespywmlileye** [comment]
> got this at the very bottom of the notebook, checking out why now:
> 
> RuntimeError: Error opening '/content/output/123764-Cheryl-Cross_0.wav': System error.
> 
> add this in botebook just above output folder:
> 
> !mkdir /content/output output_folder = "/content/output"
> 
> works crazy great! now i need to figure out how to apply that to 11M samples LOL!!!!!!!!!!!!!!!!!

Cool thanks. 

Glad to be of some assistance,  lol if you ever need help, I'm an email away ;)

**Comment by silvacarl2** [comment]
Yeah totally.  Using discrete chunks of audio like this should make things
MUCH MORE ACCURATE!!!!!!!!!!!!!!!!!!!!!
