### ISSUE TITLE
Remove pytorch and torchvision dependency

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [m-bain/whisperX#144]
If someone has already installed pytorch and torchivision in conda. On installing this package is again downloading pytorch

**Comment by sfingali** [comment]
Yes, in fact it installs a different version of pytorch from the one I want to use in Whisper (which is optimised for CUDA).

**Comment by Barabazs** [comment]
We can't just remove dependencies that are needed. It's up to you to create separate environments.
