### ISSUE TITLE
when file start with a ~10sec non speech timestamp are totally wrong

### ISSUE THREAD

**Issue by abramovi** [m-bain/whisperX#15]
I tried to run WhisperX on a file that starts with nonspeech - the initial 13 sec of the file are nonspeech.
The results WhisperX provided me ignored that silent time and start the first word in 00:00 instead of 00:14 

Any Idea?

**Comment by m-bain** [comment]
whats the timestamp of whisper for this segment before the alignment?

**Comment by RaulKite** [comment]
Try to use silero vad before whisper. It detects speech and improves timestamps when there are gaps without people talking. 

For example: 
https://gitlab.com/aadnk/whisper-webui

**Comment by abramovi** [comment]
Hey @m-bain 

Before alignment 

`{
    "id": 0,
    "seek": 0,
    "start": 0,
    "end": 0.1020408163265306,
    "text": " Hello?",
    "tokens": [
      2425,
      30
    ],
    "temperature": 0.4,
    "avg_logprob": -0.6297594197591145,
    "compression_ratio": 1.8724489795918366,
    "no_speech_prob": 0.02871905453503132,
    "word-level": [
      {
        "text": "Hello?",
        "start": 0,
        "end": 0.1020408163265306
      }
    ]
  },`
  
  After alignment
  
  `{
    "id": 0,
    "seek": 0,
    "start": 0,
    "end": 0.1020408163265306,
    "text": " Hello?",
    "tokens": [
      2425,
      30
    ],
    "temperature": 0.4,
    "avg_logprob": -0.6297594197591145,
    "compression_ratio": 1.8724489795918366,
    "no_speech_prob": 0.02871905453503132,
    "word-level": [
      {
        "text": "Hello?",
        "start": 0,
        "end": 0.1020408163265306
      }
    ]
  }`

**Comment by m-bain** [comment]
Hmm yeah the alignment assumes the original whisper timestamps are correct within 2 seconds by default. You can change this via `--align_extend` option e.g. add `--align_extend 10` for an additional ten seconds. Also yes VAD first as @raul says

**Comment by Harleyzheng** [comment]
Hi there, --align_extend is removed in the newer version and this issue still persists
