### ISSUE TITLE
Solved: Install on 3.10 and 3.11 doesnt work due to hmmlearn issue

### ISSUE THREAD

**Issue by slavovthinks** [m-bain/whisperX#150]
I had an issue installing whisperX on 3.10. It turned out it was a problem of hmmlearn library. They recently merged that:
https://github.com/hmmlearn/hmmlearn/commit/e22127765b0ca70d01976df2a369667756b8445e into master which fixes the issue but its still not available as part of a release. If you're also facing such issue just install it from git. My requirements.txt:
```
git+https://github.com/hmmlearn/hmmlearn.git
git+https://github.com/m-bain/whisperX.git
```

**Comment by kurianbenoy-sentient** [comment]
@slavovthinks is hmmlearn a dependency in WhisperX? I couldn't find it in requirements.txt?

https://github.com/m-bain/whisperX/blob/main/requirements.txt

**Comment by slavovthinks** [comment]
Its a dependency of some of its dependencies 😃 Im not sure which one exactly

**Comment by mayeaux** [comment]
Thanks!

**Comment by RazeBerry** [comment]
Had this problem as well and thankfully found this solution! Go to the hmmlearn github page and install it straight from git as opposed to pip solves it
