### ISSUE TITLE
missing pip install soundfile

### ISSUE THREAD

**Issue by Baenwort** [m-bain/whisperX#16]
Thank you for your work but unless one also does 'pip install soundfile' during the installation of this they will get an error during initialization of WhiperX.

I would suggest adding that step to the readme as even though it doesn't stop operation it does throw a warning.

**Comment by m-bain** [comment]
thank you! https://github.com/m-bain/whisperX/commit/5a668a7d8078f5a0efa62f80869c64cf00d47cca
