### ISSUE TITLE
installing on the google colab enviroment used to work, now it doesn't

### ISSUE THREAD

**Issue by tariq0101** [m-bain/whisperX#165]
as the title says, the problem appears to be related to torchtext

**Comment by Majdoddin** [comment]
Likely caused by  [`pyannote-audio#1306`](https://github.com/pyannote/pyannote-audio/issues/1306). 
You can "fix" it by  removing the torchtext, torchvision and torchdata (or installing the compatible versions), but it still does NOT do diarization. 
To remove:
```!pip install light-the-torch
!ltt uninstall torchtext torchvision torchdata -y
```
To install:
```!pip install light-the-torch
!ltt install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1  
```

**Comment by tariq0101** [comment]
Thanks a lot!, I uninstalled those using pip3 and whisperx works now again.
can I ask what is that "ltt" command? it's the first time I see it.

**Comment by Majdoddin** [comment]
You are welcome!
[light-the-torch](https://github.com/pmeier/light-the-torch) installs the right pytorch wheel for your system.
