### ISSUE TITLE
how to output joined segments for a longer on-screen session?

### ISSUE THREAD

**Issue by ClashSAN** [m-bain/whisperX#17]
generated .ass is giving constant full segments with occasional word highlighting. how to make it so the segments are joined for a longer on-screen session?

ty @m-bain, looking forward to a sweet built-in diarization implementation! This will also be very useful for quick preview of audio sound clips when searching. 

### Explanation of use-case:

-----

Would like to see if above question is easily achieved because my eyes follow the auto-generated captions on youtube videos, the scrolling, like rsvp (https://en.wikipedia.org/wiki/Rapid_serial_visual_presentation) and **I only watch videos for that reason.** It is sort of a speed reading-like tool, but instead of presenting one word at a time, which can be nausating, a more relaxed method is possible, where you can look at old text.

 These .ass files generated are possible to view with audio files on android 12 mpv, when renaming them to .srt.
A display that can hold more text than 2 lines (unlike youtube) would be ideal.

**Comment by m-bain** [comment]
Hi, you can edit the segments coming into `write_ass()` function as you wish, and edit the formatting of the `.ass.` as your application desires, but it's a bit out of scope of this repo (the subtitle output is more of just a demo)
