### ISSUE TITLE
help: highlighted subtitles according to the timestamp!

### ISSUE THREAD

**Issue by YonathanRon** [m-bain/whisperX#172]
Hi all, what's up?

First of all I really like the WhisperX project and I'm using it a lot lately.

Regarding the project, I have a tech question:
**I would like to highlight\bold\underline subtitles according to the timestamp the model gives me as an output, but I did not find code\lib that can help me do that.**
I saw a good example in your WhisperX GitHub repo:
**Could someone point me in to the relevant code\lib? it will be highly appreciated.**
 
![image](https://user-images.githubusercontent.com/29355045/231095326-d4aced09-29f2-46b6-b546-d1028b632f23.png)

Thanks ahead

**Comment by YonathanRon** [comment]
@m-bain Please assist here

**Comment by georgeoshardo** [comment]
See https://github.com/m-bain/whisperX/issues/105
