### ISSUE TITLE
`transcribe_with_vad` falls into infinite loop

### ISSUE THREAD

**Issue by coderalo** [m-bain/whisperX#174]
I noticed that the `transcribe_with_vad` function can fall into infinite loop when it gets to https://github.com/m-bain/whisperX/blob/48ed89834e6b688ad09e258c5d727569389fa15e/whisperx/asr.py#L287
If `last_timestamp_pos` is 0, it'll stop `seek` from moving forward, and thus falls into an infinite loop. A quick fix is to add `last_timestamp_pos = max(last_timestamp_pos, 1)`, but I wonder if that's the best way of fixing this.

**Comment by m-bain** [comment]
https://github.com/m-bain/whisperX/commit/6a72b61564dbea7242b8d4eab74af375df516759

**Comment by m-bain** [comment]
should be fixed with that max, like you say - there are potentially better ways to force it though. I thought openai had fixed that already :')
