### ISSUE TITLE
Support whisper max line width/count option

### ISSUE THREAD

**Issue by ahobsonsayers** [m-bain/whisperX#175]
Whisper recently added support for max line width and max line count. See https://github.com/openai/whisper/pull/1184

This is very useful because for English, [Amara.org](https://blog.amara.org/2020/10/22/create-quality-subtitles-in-a-few-simple-steps/)  and [Netflix](https://partnerhelp.netflixstudios.com/hc/en-us/articles/215274938-What-is-the-maximum-number-of-characters-per-line-allowed-in-Timed-Text-assets-) suggest it's best to keep subtitles to 42 characters per line. You can read more about the discussions surrounding this topic here https://github.com/openai/whisper/discussions/314

It would be really great is whisperx could add support for these options!

**Comment by m-bain** [comment]
supported in v3

**Comment by ahobsonsayers** [comment]
Thanks so much!
