### ISSUE TITLE
instructions on updating

### ISSUE THREAD

**Issue by Baenwort** [m-bain/whisperX#18]
You provide installation instructions. It would be nice to mention how to update in the same area of the readme so that people who know enough to follow the install line can also be given the information to update. (even if that is just to perform the same command again)

**Comment by Barabazs** [comment]
`pip install --upgrade git+https://github.com/m-bain/whisperx.git`

**Comment by m-bain** [comment]
added in https://github.com/m-bain/whisperX/commit/5a668a7d8078f5a0efa62f80869c64cf00d47cca
