### ISSUE TITLE
alignment error

### ISSUE THREAD

**Issue by cookii-king** [m-bain/whisperX#182]
!whisperx /content/audio.mp3 --model large-v2 --output_dir /content --output_format srt --max_speakers 2 --hf_token mytoken

output error:
>>Performing alignment...
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/whisperx/transcribe.py", line 213, in cli
    writer(result, audio_path)
TypeError: __call__() missing 1 required positional argument: 'options'

I don't know if i'm doing something wrong because i can get it to work on google colab properly using cli.

can someone provide a cli example for me to us, please?

**Comment by m-bain** [comment]
I think you are using the wrong version of whisper:
install this one
https://github.com/m-bain/whisperX/blob/da458863d7ee608385d1ac4de843d7755a6865a5/requirements.txt#L10

**Comment by cookii-king** [comment]
> openai-whisper==20230314

Thank you for you quick response, ill try this and let you know the results

**Comment by cookii-king** [comment]
> I think you are using the wrong version of whisper: install this one
> 
> https://github.com/m-bain/whisperX/blob/da458863d7ee608385d1ac4de843d7755a6865a5/requirements.txt#L10

Thank you that fixed the issue!

Also i had to add these lines from a previous solution to get it to work with google colab:
!pip uninstall torchtext torchvision torchdata torchtext -y
!pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1  torchtext==0.14.1
