### ISSUE TITLE
lost some lyric content

### ISSUE THREAD

**Issue by ernestzhang** [m-bain/whisperX#188]
vad detects sound, but content is not transcribed .
The content of 15 ~ 22 seconds got lost .
The content in bold is lost  

in fact the correct content is:
Ba  bà  đi  bán  lợn  con
Bán  đi  chẳng  được  lon  ton  chạy  về
**Ba  bà  đi  bán  lợn  xề  bán  đi
Chẳng  được  chạy  về  lon  ton**
Ba  thằng  cu  tí  chạy  theo  lấy  cây  chọc
Lợn  cho  kêu  rồi  cười
Ba  thằng  cu  tí  học  lười
Chúng  đi  cùng  mẹ  chọc  hoài  đàn  heo

[ba-ba-855420-16k-tail.webm](https://user-images.githubusercontent.com/1472398/233129860-035ef7c9-e926-4bf6-b845-6c7cb81a93b3.webm)

**Comment by Barabazs** [comment]
Closing since this is an old issue.

Please reopen this issue if it still persists.
