### ISSUE TITLE
[v3] intial_prompt parameter

### ISSUE THREAD

**Issue by thomasmol** [m-bain/whisperX#191]
Just saw the v3 version, looks great! I saw that it does not take the ```initial_prompt``` parameter yet (or i missed it). Will this be implemented? I've noticed it is really useful for accuracy of transcribing acronyms and names.

**Comment by m-bain** [comment]
I think it does take an initial prompt
https://github.com/m-bain/whisperX/blob/cc7e168d2b520b4a5e46d50b7c64cafac739db03/whisperx/transcribe.py#L132

If you follow asr_options through. Or at least I intended it to, let me know if you notice an issue

**Comment by thomasmol** [comment]
Ah thanks! will try this

**Comment by thomasmol** [comment]
Ok it worked, however I can only give the initial prompt at ```load_model```, is it also possible to do it at ```model.transcribe(..)``` ? Would save me some time for inference so I don't have to load the model for every new inference.

**Comment by thomasmol** [comment]
Fixed this my doing this after ```model_load```: 
```python
new_asr_options = model.options._asdict()
new_asr_options["initial_prompt"] = "Your new initial prompt"
new_options = faster_whisper.transcribe.TranscriptionOptions(**new_asr_options)
model.options = new_options
```
Just make sure to import ```faster_whisper``` as well in your script.

**Comment by busdriverbuddha** [comment]
@thomasmol Thanks for the workaround! Did it work? Is the quality the same? I'd like to use the initial_prompt to specify proper nouns for the model to look out for.

**Comment by thomasmol** [comment]
yes it worked for me @busdriverbuddha ! slight quality improvement as well.
