### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by sorgfresser** [m-bain/whisperX#192]
>   File "/venv/lib/python3.10/site-packages/whisperx/alignment.py", line 283, in align
    elif is_last or transcription[cdx+1] == " " or cdx == seg_lens_cumsum[sub_seg_idx+1] - 1:
IndexError: list index out of range

I am certain by now that it is caused by `sub_seg_idx+1` being one too large but I can't tell how to fix it.
Here is the segment where the error happens:

> {'start': 0.4809375, 'end': 23.954062500000003, 'text': 'lorem ipsum dolor sit amet', 'seg-text': ['Part1', 'Part2', 'Part3', 'Part4', 'Part5'], 'seg-start': [0.0, 5.12, 9.28, 14.96, 18.56], 'seg-end': [5.12, 9.28, 14.96, 18.56, 23.44]}

I am unable to share the transcript itself. If it is needed for debugging, I will try reproducing with a harmless example.

**Comment by m-bain** [comment]
are you using most up to date version?

https://github.com/m-bain/whisperX/blob/da458863d7ee608385d1ac4de843d7755a6865a5/whisperx/alignment.py#L283
line 283 is something else in current commit

**Comment by sorgfresser** [comment]
Just checked, I do. Just added a few print() statements beforehand, that's why my line number got messed up.
Sidenote: has been fixed by simply getting rid of the `seg-start`, `seg-text` and `seg-end` keys in the dict. 
Seems like I just couldn't use them, now I simply let `align()` assign `seg-text` for me. Sorry for bothering, does work now!
