### ISSUE TITLE
KeyError: 'word-segments' in v3 with --diarize option

### ISSUE THREAD

**Issue by prashanthellina** [m-bain/whisperX#202]
Thank you for open-sourcing the faster batched implementation. I was able to run it locally and observe the speed gain.

However, when I attempt to perform Speaker Diarization, I get this traceback. What am I doing wrong?

```
$ whisperx --model large-v2 --align_model WAV2VEC2_ASR_LARGE_LV60K_960H --batch_size 16 --compute_type float16 --output_dir out/ --task transcribe --language en --fp16 True --diarize --hf_token hf_xxxxxx  test.WAV
>>Performing transcription...
>>Performing alignment...
Failed to align segment (" Thank you."): backtrack failed, resorting to original...
Traceback (most recent call last):
  File "/home/prashanth/anaconda3/envs/whisperx/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/home/prashanth/anaconda3/envs/whisperx/lib/python3.8/site-packages/whisperx/transcribe.py", line 200, in cli
    results_segments, word_segments = assign_word_speakers(diarize_segments, result["segments"])
  File "/home/prashanth/anaconda3/envs/whisperx/lib/python3.8/site-packages/whisperx/diarize.py", line 22, in assign_word_speakers
    wdf = seg['word-segments']
KeyError: 'word-segments'
```

**Comment by m-bain** [comment]
Sorry v3 batched implementation is a prelease and I didn't test it with diarization yet.

It is not that difficult to add that functionality, but I have some other PhD work to focus on atm

**Comment by prashanthellina** [comment]
I could take a stab at it. Do you have any pointers on how I would go about it?

**Comment by prashanthellina** [comment]
@m-bain Whenever you get a chance, please look at the commit I made above. When I run the modified code, it does not fail anymore and I can see the speaker information in the output `json` file.

Do let me know if this approach is okay. If so, I will issue a pull request.

**Comment by m-bain** [comment]
yeah thats fine. I was holding off on that because there's some improvements by using the punctuation in the text to help guide the diarization (basically word-level assignments are give too much freedom and often are off-by-one word), but if you send a pull request this is good for now

**Comment by prashanthellina** [comment]
@m-bain Here is the PR #205. Thank you.

**Comment by prashanthellina** [comment]
PR was merged
