### ISSUE TITLE
Failed to align

### ISSUE THREAD

**Issue by catalwaysright** [m-bain/whisperX#21]
Thank you for this rep first!
When I tried to align an audio, I met this error.

`File"/home/ubuntu/.conda/envs/whisper/lib/python3.9/site-packages/whisperx/alignment.py", line 67, in backtrack
    raise ValueError("Failed to align")
ValueError: Failed to align "/home/ubuntu/.conda/envs/whisper/lib/python3.9/site-packages/whisperx/alignment.py", line 67, in backtrack
    raise ValueError("Failed to align")
ValueError: Failed to align`
Any idea to fix this?

**Comment by m-bain** [comment]
if you update to most recent commit:
`pip install git+https://github.com/m-bain/whisperx.git --upgrade` it should work
