### ISSUE TITLE
@V3 task "translation" not working 

### ISSUE THREAD

**Issue by gvonkreisler** [m-bain/whisperX#211]
Dear m-bain,

when I choose the --task translate the text is transcribed.

cheers george

**Comment by m-bain** [comment]
So whisperx was intended for transcribe only, since the main feature vs. others is word alignment (giving improved timestamps). Phoneme Alignment can't be done in translate mode.

is there a use to provide for `--task translate?` with batch inference?

**Comment by Alistair1231** [comment]
I like v3 whisperx since it has VAD and now also supports CT2 models. For me personally, an option to choose between transcribe with phoneme alignment and translate without it, would be great.

**Comment by m-bain** [comment]
added now in v.3.1.1 :) 

https://github.com/m-bain/whisperX/releases/tag/v3.1.1
