### ISSUE TITLE
Can't get segments short enough even with max_line_width and max_line_count

### ISSUE THREAD

**Issue by NielsVandenEynde** [m-bain/whisperX#218]
I get segments that are 20 seconds long but this is too much for my usecase. I tried what you suggested in #200 but it's not working.

I would need segments that are max 12 seconds long.
Any suggestions?

**Comment by m-bain** [comment]
how do you mean its not working? I would suggest using the word timestamps, build your own segments, but grouping words than span no longer than 12s together (you can prioritize punctuation breaks for more natural segments)

**Comment by NielsVandenEynde** [comment]
OK so I looked into the code and saw that when you output to json, which was what I was doing, it completely ignores those options and just dumps it. Don't know if that's intended functionality. With srt it works, however it does just cut off mid sentence.

I will probably do as you suggested and build my own segments.

**Comment by m-bain** [comment]
Yes this is intended, line options are just for subtitles (srt) file
