### ISSUE TITLE
Question: Is all processing of audio done locally?

### ISSUE THREAD

**Issue by Juergen-J-F** [m-bain/whisperX#227]
Hi and first of all thanks for the great work. 

I have a question regarding the documentation, as it did not become clear to me ifthe diarization models are used locally. I.e., are they downloaded and used locally or is the audio data at any point sent to an outside server?

Thanks for clarifying.

Best,
Jürgen

**Comment by prashanthellina** [comment]
All computation is done locally. Only the models are pulled from the internet for the first time and cached for subsequeuent runs.

**Comment by Juergen-J-F** [comment]
Thanks, that makes using it much easier for reasearch projects.
