### ISSUE TITLE
Phoneme-level timestamps

### ISSUE THREAD

**Issue by MichaelDoron** [m-bain/whisperX#23]
Great work!
Is it possible to expand this to phoneme-level timestamps, instead of word-level timestamps?

For example, instead of 
"[00:13.50->00:13.60] smiles"
have
"[00:13.50->00:13.53] s
[00:13.53->00:13.57] mi
[00:13.57->00:13.58] l
[00:13.58->00:13.60] es"

**Comment by m-bain** [comment]
added in d395c21b8399cb2f29643a75f91469917cdbb991
