### ISSUE TITLE
Text-Tuple not unpacked

### ISSUE THREAD

**Issue by sorgfresser** [m-bain/whisperX#231]
In [2efa136114a3ad677a76c8e7b9e75008b3bb4f60/whisperx/asr.py#L245 ](https://github.com/m-bain/whisperX/blob/2efa136114a3ad677a76c8e7b9e75008b3bb4f60/whisperx/asr.py#L245) we are setting `text` (unpacking the tuple) but are not using it afterwards. Shouldn't line 248 be `"text": text`?

**Comment by m-bain** [comment]
ah good find! Yes thats needed for non-batched call, you can PR that if you want
