### ISSUE TITLE
Prompts using batch inference

### ISSUE THREAD

**Issue by sorgfresser** [m-bain/whisperX#234]
If I am not mistaken the prompt parameter used in the original whisper is not utilized the same way in batch inference.
Does this have measurable negative implications regarding accuracy?

**Comment by m-bain** [comment]
Hi, yes currently the same prompt is given to every segment (sample) in the audio (batch).

This is different to openai's implementation where its just given to the first segment in the audio file. There's some additional differences written here https://github.com/m-bain/whisperX/blob/main/README.md#technical-details-%EF%B8%8F

But we found in the paper these changes overall actually improved accuracy slightly and led to less hallucination overall. However, there are quite a few changes and its possible some worsen accuracy whilst others improve accuracy

<img width="1130" alt="Screenshot 2023-05-09 at 11 59 19" src="https://github.com/m-bain/whisperX/assets/36994049/f9e4b6bb-aaaf-4ce5-a461-7f7850668dff">

**Comment by sorgfresser** [comment]
Very interesting! I'll refer to the paper for more information.
