### ISSUE TITLE
Windows install issues

### ISSUE THREAD

**Issue by jake1271** [m-bain/whisperX#237]
Has anyone been able to install on windows?  If you have, could you share the steps you took?

I've gone though the ReadMe steps and even tried installing CUDA toolkit, but doesn't affect the error I'm getting when installing:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.2 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.

I've tried upgrading to 2.0.1, but then I get more complaints and still doesn't run.

**Comment by moriend** [comment]
I had the same problem as you and I solved it like this


conda create --name whisperx python=3.10
conda activate whisperx

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia


modify  requirements.txt 

torch==2.0.1
torchaudio==2.0.2

pip install -e .


that works for me

**Comment by jake1271** [comment]
It worked!  Thanks sooo much!!!

**Comment by xorlof** [comment]
I had the same issue last week. 

The install instructions in the readme that were updated a few days ago (after this issue was opened). Following these new instructions fixes this issue.
