### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by GeoRCode** [m-bain/whisperX#243]
I'm just importing this two lines in my code:
```python
from whisperx import load_align_model, align
from whisperx.diarize import DiarizationPipeline, assign_word_speakers
```
And then using them like this:
```python
diarization_pipeline = DiarizationPipeline(use_auth_token=hf_token)
diarization_result = diarization_pipeline(audio_file)
```
This the ends up calling `diarize.py` where the issue pops at **line 28** over the function `assign_word_speakers`.

On my code, I'm giving my **hf token** and the **wav audio file** as parameters. Any idea of what's going on or what am I doing wrong?

**Comment by m-bain** [comment]
Can you give the full example? In your example `assign_word_speakers` is not called so im unsure how it can throw an error.

You can see https://github.com/m-bain/whisperX/blob/main/README.md#python-usage--
for example python usage

**Comment by GeoRCode** [comment]
Hi, sorry.

Can you delete the issue report? I'm so sorry for the inconvenience, I didn't realize the `assign_word_speakers` function changed since the original code was written. I had two errors in my code that I already resolved pretty easily once I check the function in detail.

Thanks anyways :)

**Comment by ael-bagh** [comment]
Hi can you please share your solution ? @GeoRCode

**Comment by GeoRCode** [comment]
Hey @ael-bagh, sure!

My issue was that I had the original code like this:
```python
result_segments, word_seg = assign_word_speakers(diarization_result, aligned_segments["segments"])
```
As I said before, this ends up calling **diarize.py** on whisperx, where an the error pops at **line 28**:
```python
def assign_word_speakers(diarize_df, transcript_result, fill_nearest=False):    --> 27 
    transcript_segments = transcript_result["segments"]                         --> 28
```
The problem was that I was trying to pass just the "segments" section of my variable, where the function `assign_word_speakers` already does it.
Also, I was trying to get two returned objects where the function only returns one:
```python
return transcript_result                                                        --> 59
```
In fact, you actually don't have to assign a variable to get the returned object cause the function works by modifying the original diarization result you're giving to it in first place.
So yeah, pretty basic here. My bad, I didn't realize 😅
