### ISSUE TITLE
Diarization Fails with mp4/HF Token Always Required

### ISSUE THREAD

**Issue by ccos89** [m-bain/whisperX#245]
Hi, two quick questions.

1. Whisper transcription (thereby WhisperX) ordinarily works on video files including the .mp4 extension.  However, pyannote does not appear to support mp4 files, as whenever I try to use diarization on an mp4 file, I get the following error: Error opening 'mdi.mp4': Format not recognised.

One can simply convert the mp4 to a wav and thereafter use the diarization on that through ffmpeg with `$ ffmpeg -i mdi.mp4 mdi.wav`.  While it's not a big deal to do that, since ffmpeg is a prereq to using Whisper anyway, is it something that could be coded in in the future that when WhisperX is run with --diarize on an .mp4, it automatically creates a wav file through ffmpeg, processes that file in lieu of the mp4, and then deletes the wav when the process is complete?

2. I see from a closed issue that use of the huggingface gated repos for diarization is allegedly an offline process after the first time - however, use of --diarize requires me to input the --hftoken argument every time.  If I don't, I get an authentication error.  I see from [this FAQ](https://github.com/pyannote/pyannote-audio/blob/31143e0d44116362432a338034c5f167bcea9a85/FAQ.md) on pyannote that it is possible to download the pipelines and edit a config.yaml file to point to the local file rather than going through the authentication process each time.  
I'm looking to use whisperX on an offline machine. Is there a way that this offline pipeline method is compatible with whisperX?  As a novice, I'm not really sure where I'm supposed to be putting the config.yaml and the pytorch_model.bin files - and even if I figure that out, I'm not sure if that's going to work properly with whisperx, or if whisperx is mandating pyannote to go through the online authentication process.

Thanks in advance, and thanks for the awesome work with WhisperX, it is phenomenal.

**Comment by ccos89** [comment]
For those who need additional guidance:

1.	Navigate to the repository [pyannote/speaker-diarization-3.1](https://huggingface.co/pyannote/speaker-diarization-3.1/tree/main), accept the agreement to get past the gate and be able to view the Files and Versions tab, and download the file **config.yaml** by hitting the little square download button to the right of the file name.  That's the only file we need.

2.	Navigate to the repository [pyannote/segmentation-3.0](https://huggingface.co/pyannote/segmentation-3.0/tree/main), accept the agreement to get past the gate and be able to view the Files and Versions tab, and download the file **pytorch_model.bin** by hitting the little square download button to the right of the file name.  That's the only file we need..

3. Once you've downloaded both files (config.yaml and pytorch_model.bin), stick them together inside a folder.  The folder can be anywhere on your computer, but I recommend putting it in a folder inside your conda environment install directory.  For example, I recommend using the folder path:

     `"C:\Users\YourUsername\miniconda3\envs\whisperx"`

    and then creating a new subfolder called "offline" or something wherein you put the two files.
    
    *This ensures that if you delete your entire conda environment to either uninstall or reinstall the program, this data will also be deleted.*

4.	Open config.yaml in a text editor and edit the line that says segmentation to point towards the pytorch_model.bin file we downloaded and put in our local folder instead of towards the directory on huggingface. You should use the absolute file path inside single quotations, like the following example:

    `segmentation: ‘C:\Your\File\Path\Here\pytorch_model.bin’`

5. Open diarize.py located within the whisperx package within your whisperx conda environment (example folder path: `C:\Users\YourUsername\miniconda3\envs\whisperx\Lib\site-packages\whisperx`).  

    Edit line 13 to change the model name to be the absolute file path to the config.yaml file above, but replacing any of the backslashes with forward slashes, for example:
    `model_name="C:/Your/File/Path/Here/config.yaml",`

&#127881;&#127881; Congratulations! Your installation of whisperx will no longer rely on the internet at all, as you have replaced the dependency on the gated pyannote models and pipelines on huggingface with local versions hosted on your own machine.  This means you do not need to use a huggingface token at all like it says in whisperx documentation.
	
&#x1F310;&#x1F6AB; Remember when dealing with sensitive data, you can validate that you are running the program completely offline after following these instructions by disconnecting your internet and testing the program.

**Comment by alaskann** [comment]
> For those who need additional guidance:
> 
>     1. Navigate to the repository [pyannote/speaker-diarization-3.1](https://huggingface.co/pyannote/speaker-diarization-3.1/tree/main), accept the agreement to get past the gate and be able to view the Files and Versions tab, and download the file **config.yaml** by hitting the little square download button to the right of the file name.  That's the only file we need.
> 
>     2. Navigate to the repository [pyannote/segmentation-3.0](https://huggingface.co/pyannote/segmentation-3.0/tree/main), accept the agreement to get past the gate and be able to view the Files and Versions tab, and download the file **pytorch_model.bin** by hitting the little square download button to the right of the file name.  That's the only file we need..
> 
>     3. Once you've downloaded both files (config.yaml and pytorch_model.bin), stick them together inside a folder.  The folder can be anywhere on your computer, but I recommend putting it in a folder inside your conda environment install directory.  For example, I recommend using the folder path:
>        `"C:\Users\YourUsername\miniconda3\envs\whisperx"`
>        and then creating a new subfolder called "offline" or something wherein you put the two files.
>        _This ensures that if you delete your entire conda environment to either uninstall or reinstall the program, this data will also be deleted._
> 
>     4. Open config.yaml in a text editor and edit the line that says segmentation to point towards the pytorch_model.bin file we downloaded and put in our local folder instead of towards the directory on huggingface. You should use the absolute file path inside single quotations, like the following example:
>        `segmentation: ‘C:\Your\File\Path\Here\pytorch_model.bin’`
> 
>     5. Open diarize.py located within the whisperx package within your whisperx conda environment (example folder path: `C:\Users\YourUsername\miniconda3\envs\whisperx\Lib\site-packages\whisperx`).
>        Edit line 13 to change the model name to be the absolute file path to the config.yaml file above, but replacing any of the backslashes with forward slashes, for example:
>        `model_name="C:/Your/File/Path/Here/config.yaml",`
> 
> 
> 🎉🎉 Congratulations! Your installation of whisperx will no longer rely on the internet at all, as you have replaced the dependency on the gated pyannote models and pipelines on huggingface with local versions hosted on your own machine. This means you do not need to use a huggingface token at all like it says in whisperx documentation.
> 
> 🌐🚫 Remember when dealing with sensitive data, you can validate that you are running the program completely offline after following these instructions by disconnecting your internet and testing the program.

Hey, thanks for posting these details. Unfortunately I am running into an issue when executing the example file under the whisperX github docs.

```
Traceback (most recent call last):
  File "c:\Users\name\dev\pystuff\app.py", line 41, in <module>
    diarize_model = whisperx.DiarizationPipeline(device=device)
```

This error also persists when I use the following `diarize_model = whisperx.DiarizationPipeline(use_auth_token="", device=device)` 

How does method this change use of the diarize_model?
