### ISSUE TITLE
Long file issue

### ISSUE THREAD

**Issue by goodPointP** [m-bain/whisperX#250]
Getting an error:

`
ValueError: Invalid input features shape: expected an input with shape (1, 80, 3000), but got an input with shape (1, 80, 4203) instead
`

Running inside Google Colab, It gets stuck at the model.transcribe() step for a ~58 minutes long WAV file.

When I shortened the file and retried it worked, implying it has something to do with audio length?

**Comment by sorgfresser** [comment]
Could you provide additional traceback on this error? And even further: what command line options did you use?

**Comment by m-bain** [comment]
Solved in [this recent bugfix ](https://github.com/m-bain/whisperX/commit/42b4909bc07ccad388acf86818d8c0da8482bc71)
