### ISSUE TITLE
Suggested enhancement: increase length of resulting segments

### ISSUE THREAD

**Issue by oep42** [m-bain/whisperX#26]
![increase length of resulting segments](https://user-images.githubusercontent.com/84353335/211605228-45dfc44c-219b-4190-99c1-cca5dc764fc0.png)
I assume that the resulting segments resemble the black lines in the image. In the image, the segments have been lengthened at the beginning (red line), and at the end (green line).

Is it possible to add parameters for the optional lengthening of all the resulting segments at the beginning and at the end?

[parameter 1:] The red line is an example of the result of a parameter to lengthen all segments at the beginning (in milliseconds). 

[parameter 2:] The green line is an example of the result of a parameter to lengthen all segments at the end (in milliseconds). 

[parameter 3:] A third parameter is for the minimum distance (in milliseconds) between the end of a (lengthened) segment and the beginning of the next (lengthened) segment. This third parameter may overrule the other two parameters to prevent a collision.

**Comment by m-bain** [comment]
Mmm this is just post-processing on the timestamp (not specific to the alignment), you should be able to do this to the `.srt` files
