### ISSUE TITLE
Sizes of tensors must match except in dimension 0.

### ISSUE THREAD

**Issue by metheofanis** [m-bain/whisperX#264]
I try to run the example here.
I get error at line:
`diarize_segments = diarize_model(audio_file)`

if I comment out the diarization part, is working as expected!

The error is:

> Sizes of tensors must match except in dimension 0. Expected size 80000 but got size 77997 for tensor number 19 in the list.
>   File ".../Transcribe/transcribe.py", line 112, in whisper_files
>     diarize_segments = diarize_model(audio_file)
>   File ".../Transcribe/transcribe.py", line 154, in <module>
>     whisper_files(get_audio_files())

**Comment by mkosecki** [comment]
The problem is with padding in pyannote or deeper, that is torchaudio. I took a fast research and this showed up https://github.com/pyannote/pyannote-audio/pull/1326

**Comment by sinisuba** [comment]
I've had the same issue but not quite sure how I got it fixed. Did you try using **float32** _compute_type_, as well as lowering the _batch_size_? The align model I used was **WAV2VEC2_ASR_BASE_960H**, and the **small.en** Whisper model.
I got the desired results afterwards:
``24:26.402 --> 24:27.903 [SPEAKER_03]: You could really do some cool things.``

**Comment by moog500nl** [comment]
Yes, I have the same issue. Made your adjustments but still the same error.

**Comment by metheofanis** [comment]
Maybe there is not enough VRAM for diarization? I have 12GB.
I have to use large model for Greek. The align model is chosen automatically. I've not specified any.
The size of my files is ~50MB and about 55 min long!

**Comment by sinisuba** [comment]
I ran mine on an 8 GB VRAM Nvidia GPU, and the test audio was ~45 mins long. Had the same issue, but then it got resolved. I doubt it's the hardware.

**Comment by sinisuba** [comment]
> Problem fixed. The audio had a small portion at the beginning, which was not English. I forced it to --language en, but I guess it was still choking on that part because I stripped it out and THEN it worked fine.

Interesting. I remember using `--language en` even when I had the issue, and I don't remember it helping. Maybe it's related to a mismatch between `--language` and `--align_model`.

**Comment by moog500nl** [comment]
Oddly enough, it failed again on a different MP3 (all in English) for me
just now. I suspect Sinisa has zeroed in on the issue.

**Comment by metheofanis** [comment]
It looks like this error in coming from pyannotate.

I found [this issue.](https://github.com/pyannote/pyannote-audio/issues/937)
It looks like it is fixed from [this issue](https://github.com/pyannote/pyannote-audio/pull/1002).

I wonder how to use it. Maybe I have to wait?

**Comment by NeubertJonas** [comment]
I successfully resolved the same issue by converting my files to .wav as well.

**Comment by baer** [comment]
Same. Converting to wav fixed the problem for me. For anyone who needs it, here's a bit of Python I used for that conversion

```py
def convert_mp3_to_wav(input_path: str, output_path: str):
    try:
        ffmpeg.input(input_path).output(output_path).run(overwrite_output=True)
    except ffmpeg.Error as e:
        print(f"ffmpeg error: {e.stderr.decode()}")
        raise RuntimeError(f"Failed to convert mp3 to wav: {e.stderr.decode()}") from e
    except Exception as e:
        print(f"General error: {str(e)}")
        raise e
```

**Comment by baer** [comment]
Update: It looks like @m-bain [wrote a function](https://github.com/m-bain/whisperX/blob/main/whisperx/audio.py#L56C1-L79C17) that may be intended to fix this. It is not used anywhere in the project and is not exported. Is this dead code, or could this be a part of the solve?

**Comment by baer** [comment]
Tagging Related Issues: https://github.com/m-bain/whisperX/issues/322, https://github.com/m-bain/whisperX/issues/275, https://github.com/m-bain/whisperX/issues/366

**Comment by guilhermehge** [comment]
For me, I used [this function](https://github.com/guillaumekln/faster-whisper/blob/5a0541ea7d054aa3716ac492491de30158c20057/faster_whisper/audio.py#L19)

along with this piece of code:

```
audio = decode_audio(audio, sample_rate)
audio_data = {
    'waveform': torch.from_numpy(audio[None, :]),
    'sample_rate': sample_rate
}

diarization = pipeline(audio_data)
```

And it accepted my mp3 file. I also converted it to .wav to test it and got the same results.

It is also possible to use [this function](https://github.com/openai/whisper/blob/0a60fcaa9b86748389a656aa013c416030287d47/whisper/audio.py#L26) along with the code I just mentioned. Same results.

**Comment by metheofanis** [comment]
I think I should close this issue, since I'm not getting it with newer version. We also have so many workarounds. Thanks all!!!

**Comment by brendankntb** [comment]
I'll add another workaround to the mix. I had been using the conversion to .wav to avoid the error but I also found that the error no longer occurred when I loaded the file into memory before processing with:

waveform, sample_rate = torchaudio.load(audio_file)
diarization = pipeline({"waveform": waveform, "sample_rate": sample_rate})

I was doing this to speed up diarization (which it did) but it also stopped me getting the tensor size mismatch.
