### ISSUE TITLE
I want add a wav2vec model for Vietnamese

### ISSUE THREAD

**Issue by Mr-Turtleeeee** [m-bain/whisperX#276]
I try to push code but i received a error:
```
remote: Permission to m-bain/whisperX.git denied to Mr-Turtleeeee.
fatal: unable to access 'https://github.com/m-bain/whisperX.git/': The requested URL returned error: 403
```

**Comment by Mr-Turtleeeee** [comment]
Did you block push code to this repo?

**Comment by callmephilip** [comment]
@Mr-Turtleeeee you have to fork this repo, branch and submit a pull request

**Comment by Mr-Turtleeeee** [comment]
> @Mr-Turtleeeee you have to fork this repo, branch and submit a pull request

hmm, i cloned your project and edited it but I don't know why it shows the above error. Did I take any steps?

**Comment by Mr-Turtleeeee** [comment]
@callmephilip Hmm, I have made 1 pull requests, can you take a look at it?

**Comment by m-bain** [comment]
merged :)
