### ISSUE TITLE
Got IndexError: list index out of range

### ISSUE THREAD

**Issue by ohmygoobness** [m-bain/whisperX#29]
At the Performing alignment... part got IndexError: list index out of range error  
whisperx --model large --task translate --language ja movie.mp4 --align_model jonatasgrosman/wav2vec2-large-xlsr-53-japanese

![cmd_mi3f2FHNZm](https://user-images.githubusercontent.com/82442572/212074140-4a42833a-89cd-4363-b139-2cc355cb72de.png)

**Comment by m-bain** [comment]
mm looks like you are using old version which has a bug can you run:
`pip install git+https://github.com/m-bain/whisperx.git --upgrade`
