### ISSUE TITLE
Accuracy of Transcription: Filler words

### ISSUE THREAD

**Issue by skartekko** [m-bain/whisperX#293]
Hi there, when transcribing with whisperX, not all words that are said (e.g. filler words or repetitions) are transcribed. 
How can I make sure that all words, including filler words or word repetitions, are transcribed? What parameters influence the word accuracy of the transcription?
Thank you!

**Comment by m-bain** [comment]
Yes this is due to Whisper. You could try prompting whisper to transcribe filler words like:

`--initial_prompt Now, umm.. watch uhh.. this video`

**Comment by skartekko** [comment]
Thanks, so I define the words that should not be omitted. But how can I set that word repetitions are taken into account in the transcription?

**Comment by skartekko** [comment]
And one more question for using the intial_prompt in the Python library and not as CLI:

I am getting an error message when using the intial_prompt argument. It seems that the transcribe method of the FasterWhisperPipeline class does not accept an initial_prompt argument. Does that means that the WhisperX Python library (3.1.1), as it is currently implemented, cannot provide an initial prompt for the transcription?

**Comment by m-bain** [comment]
`model = load_model(
          'large_v2',
          device='cuda',
           asr_options={"initial_prompt": "Now, umm.. watch uhh.. this video"})`

**Comment by m-bain** [comment]
np, let me know if the prompt was successful in improving transcription of filler words, and if yes feel free to close the issue :)

**Comment by skartekko** [comment]
Yes, the prompt has improved the transcription of filler words.
Thanks for the quick reply!

**Comment by sbersier** [comment]
When it comes to the Python API, I think the following is better since you can change the initial prompt without reloading the model.
Note that a lot of options can be accessed that way (beam_size, patience, length_penalty, repetition_penalty, no_repeat_ngram_size, log_prob_threshold, no_speech_threshold, compression_ratio_threshold, condition_on_previous_text, prompt_reset_on_temperature, temperatures, initial_prompt, prefix, suppress_blank, suppress_tokens, without_timestamps, max_initial_timestamp, word_timestamps, prepend_punctuations, append_punctuations, multilingual, max_new_tokens, clip_timestamps, hallucination_silence_threshold, hotwords)


```
import whisperx

device = "cuda" 
audio_file = "a.wav"

# Load model
model = whisperx.load_model("medium", device, language='fr')

# Give an initial prompt with the expected filler words:
model.options.initial_prompt="Bon, heu, voilà. Voilà, voilà. Alors, heu, mmh. Enfin j'veux dire que, heu, hein, enfin. Alors, hem, mmh, hmm, heum"

# Transcribe:
result = model.transcribe(audio_file,language='fr')
```

**Comment by lececefifi** [comment]
The initial prompt is extremely useful for English language. Anyone have successfully gotten these filler words out of Dutch audio files?  I have tried the following prompts, but it hasn't been useful so far. Anyone would share their prompt for Dutch?

"Eh, ik denk, hmm... Oké, uh, dit is wat ik aan het denken ben."
"“Umm, uh, ah, laat me denken, hmm... Oké, hm, dit is wat ik denk, hm.”

**Comment by LaurinmyReha** [comment]
This should help a lot with dutch and multilingual verbatim transcription in general :) 
https://github.com/nyrahealth/CrisperWhisper
