### ISSUE TITLE
Reverting pyannote and torch versions recommended?

### ISSUE THREAD

**Issue by federerfanatic** [m-bain/whisperX#306]
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0. Bad things might happen unless you revert torch to 1.x.

Note I am running this in a conda environment under Ubuntu 22.04. 

Seems to work with my versions.

Q. How do I distinguish speakers in the output files? It would nice if the output format would indicate this more clearly.

**Comment by sorgfresser** [comment]
Ignore the warnings, they are intended. Regarding the question: refer to the json maybe, there you got an extra key for each segment showing the speaker. I find the json easiest to work with and simply apply my own normalization afterwards.

**Comment by gsyllas** [comment]
Hello, did you solve this error?

**Comment by Barabazs** [comment]
You can ignore the warnings. See https://github.com/m-bain/whisperX/issues/546#issuecomment-1792848345 for more info.
