### ISSUE TITLE
"word-level" doesn't always exist

### ISSUE THREAD

**Issue by NodudeWasTaken** [m-bain/whisperX#31]
I tried to translate from japanese to english and use whisperx.
In exactly one entry it's missing a "word-level" in it's alignment dict, causing `utils.write_ass` to fail.

Alignment output entry:
>         {
>             "id": 654,
>             "seek": 518644,
>             "start": 5198.74,
>             "end": 5198.7404,
>             "text": " Shizu",
>             "tokens": [
>                 1160,
>                 590,
>                 84
>             ],
>             "temperature": 1,
>             "avg_logprob": -4.464975124452172,
>             "compression_ratio": 1.0123456790123457,
>             "no_speech_prob": 0.07407991588115692
>         },

**Comment by tomlinsonm** [comment]
Probably redundant, but it comes in when the segment has an invalid timestamp - either greater than max duration or smaller than the allowed precision.

**Comment by m-bain** [comment]
fixed in recent commit I think d395c21b8399cb2f29643a75f91469917cdbb991
