### ISSUE TITLE
Output quality degradation after converting HF model to CT2

### ISSUE THREAD

**Issue by vsokolovskii** [m-bain/whisperX#313]
- I'd like to get the word-level time-stamped output from my HF whisper checkpoint
- I convert my checkpoint to the ct2 format to load it to the whisperx `ct2-transformers-converter --model my_hf_ckpt --output_dir ct2_ckpt`
- after loading the ct2_ckpt with whisperx the transcription quality degrades significantly (example: `t three we are t t the time is ten three we are ten three ten ten three we all the case court`)

What can be the problem?
- precision (f16, f32)??
- conversion is bad
- HF checkpoint is bad?

I'll be happy to hear any guesses and pieces of advice

**Comment by arnavmehta7** [comment]
I haven't experienced anything like this.

**Comment by m-bain** [comment]
i think post this on
 https://github.com/guillaumekln/faster-whisper
