### ISSUE TITLE
Cuda failed with error out of memory

### ISSUE THREAD

**Issue by arnavmehta7** [m-bain/whisperX#315]
I just updated my whisperx version and I am unexpectedly getting `cuda failed with error out of memory` after sometime of running

**Comment by arnavmehta7** [comment]
`Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.`
Also I am getting things like these

**Comment by m-bain** [comment]
How much memory does your GPU have? You can reduce batch size or size of model.


> Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.

you can ignore those warnings

**Comment by arnavmehta7** [comment]
16gb VRAM, large-v2, 20 batch size :(

**Comment by arnavmehta7** [comment]
erm it's stuck now
