### ISSUE TITLE
not an issue, just a question: are wav versus mp3 files more accurate in time stamps?

### ISSUE THREAD

**Issue by silvacarl2** [m-bain/whisperX#319]
are wav versus mp3 files more accurate in time stamps?

what is recommend best practice?

carl

**Comment by RimaAisulu** [comment]
In my case timetsamp accuracy seems to degrade as we go further into mp3 audio, haven't tried wav yet. It's accurate at the beginning but after ~5 minutes it gradually starts degrading, leading up to 20 mismatch with 20-30 minute audio files.

**Comment by silvacarl2** [comment]
got it.  ours are fairly short recordings of phone calls
