### ISSUE TITLE
I built a container to run whisperX via API on runpod 

### ISSUE THREAD

**Issue by werkamsus** [m-bain/whisperX#331]
Hey @m-bain ,

I built a container + config to run this on https://runpod.io/ as a serverless function. Makes it super easy to embed into apps.

Code is a little spaghetti, but just thought I'd share here:
https://github.com/werkamsus/whisperX-runpod-container

I suck at OSS so lmk if you want me to integrate it here. If code quality too low, let me know :D 

Works without errors though if you just add the docker container to runpod + the env var HF_TOKEN.

Cheers from Berlin

Nick

**Comment by lgandecki** [comment]
Hi @werkamsus , I had the tab with your repo open and planned to play around with it, why did you remove it? :) Are you planning to make it public again at some point?

**Comment by werkamsus** [comment]
Hey @lgandecki , just fixed it :) it's accessible again. Let me know if you need help getting it to run!

**Comment by lgandecki** [comment]
@werkamsus I still get 404 using that link, did you try opening it from incognito?

**Comment by briankariuki** [comment]
I also got a 404 error
