### ISSUE TITLE
No transcript generated when diarizing large files (> 750 MB) 

### ISSUE THREAD

**Issue by Barabazs** [m-bain/whisperX#332]
I have a few large WAV files >750MB  and > 70 min long. 
Running the command below without `--diarize` works like expected and generates the transcript files.
But when adding `--diarize` it runs until the end and then exits without generating the appropriate files. There is no error, no warning, no crash,.... It finishes as if it was completed successfully.

Command used: 
`whisperx FILENAME --model large-v2 --align_model WAV2VEC2_ASR_LARGE_LV60K_960H --batch_size 32 --compute_type float32 --diarize --hf_token xxxxxxxxxxxxxxx --language en --output_format all --output_dir "/tmp/xxx"
`

**Comment by sam1am** [comment]
Are you running out of memory? You might need to split the file first and do it in chunks.

**Comment by Barabazs** [comment]
> Are you running out of memory? 

Not that I'm aware of. There are no errors, warnings or crashes.

> You might need to split the file first and do it in chunks.
I'm doing that manually at the moment, but it's a pain for labeling speakers, so it's not a solution.

**Comment by Barabazs** [comment]
Issue has been resolved with one of the changes between then and now. Closing this.
