### ISSUE TITLE
Adding options in the Python API

### ISSUE THREAD

**Issue by mirix** [m-bain/whisperX#335]
Hello,

I would like to add some extra options to the Python API example.

For instance: align_model='WAV2VEC2_ASR_LARGE_LV60K_960H', output_dir='diarisamples', output_format='srt'

How do I do that?

Best,

Ed

**Comment by jun297** [comment]
you can check here:
https://github.com/m-bain/whisperX/blob/befe2b242eb59dcd7a8a122d127614d5c63d36e9/whisperx/alignment.py#L54
https://github.com/m-bain/whisperX/blob/befe2b242eb59dcd7a8a122d127614d5c63d36e9/whisperx/asr.py#LL25C16-L25C16

**Comment by mirix** [comment]
So, should it be here?

`result = whisperx.align(result['segments'], model_a, metadata, audio, device, return_char_alignments=False, align_model='WAV2VEC2_ASR_LARGE_LV60K_960H')`

Or should I call it model_name?

One more question, what about beam_size? Wherever I put it, is not recognised.

**Comment by Barabazs** [comment]
Hi @mirix, all these options can be set when using the CLI or if you want to do it programmatically, you can also use sys.argv or any other python technique.
