### ISSUE TITLE
model.bin path ?? 

### ISSUE THREAD

**Issue by 4698to** [m-bain/whisperX#337]
An error occured while synchronizing the model guillaumekln/faster-whisper-large-v2 from the Hugging Face Hub:

https://huggingface.co/guillaumekln/faster-whisper-large-v2/tree/main

models--guillaumekln--faster-whisper-large-v2\refs\main\model.bin

Which path is the file placed in? @prashanthellina

**Comment by fengpeng-yue** [comment]
I have the same issue.

**Comment by ricardojeq** [comment]
whisperx uses the huggingface models. Those can be found under C:\Users\<username>\.cache\huggingface\hub\models--guillaumekln--faster-whisper-<modelname>\snapshots.

**Comment by 4698to** [comment]
> Whisperx使用Huggingface模型。这些可以在C：\Users<username>.cache\huggingface\hub\models--guillaumekln--faster-whisper-\snapshots下找到。
<img width="1391" alt="Screenshot 2023-07-03 223152" src="https://github.com/m-bain/whisperX/assets/18095923/df9734a6-1404-4fb8-98b9-95a6e31a8558">

I manually created it ，but it didn't work.

**Comment by 4698to** [comment]
> whisperx uses the huggingface models. Those can be found under C:\Users<username>.cache\huggingface\hub\models--guillaumekln--faster-whisper-\snapshots.

My network environment cannot connect to https://huggingface.co/models， These models can only be downloaded using Internet Download Manager on the Edge browser.

**Comment by ricardojeq** [comment]
> > Whisperx使用Huggingface模型。这些可以在C：\Users.cache\huggingface\hub\models--guillaumekln--faster-whisper-\snapshots下找到。
> 
> <img alt="Screenshot 2023-07-03 223152" width="1391" src="https://user-images.githubusercontent.com/18095923/250585460-df9734a6-1404-4fb8-98b9-95a6e31a8558.png">
> I manually created it ，but it didn't work.

For this issue, did you manually create the "main" file? The contents of the main file is the subfolder name (in bold) under snapshot. For example, C:\Users\<username>\.cache\huggingface\hub\models--guillaumekln--faster-whisper-large-v2\snapshots\**22b32386e4012f0e7a5c13657821ea11626b0daf**.

**Comment by ricardojeq** [comment]
> > whisperx uses the huggingface models. Those can be found under C:\Users.cache\huggingface\hub\models--guillaumekln--faster-whisper-\snapshots.
> 
> My network environment cannot connect to [https://huggingface.co/models，](https://huggingface.co/models%EF%BC%8C) These models can only be downloaded using Internet Download Manager on the Edge browser.

Did you try to delete the models--guillaumekln--faster-whisper-large-v2 directory and re-download the model when you use whisperx? Did you try using VPN?

**Comment by 4698to** [comment]
<img width="817" alt="Snipaste_whisperX_model2" src="https://github.com/m-bain/whisperX/assets/18095923/365008f5-06b0-4cfd-b406-9544f9ca1671">

**Comment by jiezi4ai** [comment]
I have got the same issue here. It took me serveral hours to get it through.

## Short answer: 
**WhisperX and faster-whisper use CTranslate2 for acceleration. You need to first convert whisper (huggingface version) to the version supported by CTranslate2 before using it.**

## Long answer:
I could not access to Huggingface on my server. Have to mannually download whisper from ModelScope (https://modelscope.cn/models/AI-ModelScope/whisper-large-v3/files) and set up the code as in @4698to 's case.

On this issue, I have checked the source code. For whisperX, I started from load_model function in 'transcribe.py' to WhisperModel class in 'asr.py'. It actually points to faster-whisper's [WhisperClass](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py)

From line 133, you could find it uses CTranslate2 to load whisper model. Based on [CTranslate2 manual](https://opennmt.net/CTranslate2/guides/transformers.html#whisper), it specifies that transformer model has to be first converted (model quantization) before it could be used here.

## Step-by-Step solution
1. First convert your whisper model to the ct2 form using the following code:
   `ct2-transformers-converter --model openai/whisper-tiny --output_dir whisper-tiny-ct2`
   _openai/whisper-tiny_ refers to the path of your local whisper path (huggingface version), while _whisper-tiny-ct2_ is the local folder save converted version.
   ct2-transformers-converter command comes from CTranslate2 which was installed as dependency with whisperX or faster-whisper.

2. Download _'tokenizer.json'_ from Huggingface and put it under _whisper-tiny-ct2_ folder.
   Be mindful that CTranslate2 would also load tokenizer.json file when using whisper. You have to mannually download it from huggingface and put it onto your local folder (the converted whisper). 
   BTW, there is no tokenizer file in  Whisper on ModelScope platform.

3. Now you could apply whisperX or faster-whisper using local model, sample code as follows:
   `model = whisperx.load_model(
            local_ct2_whisper_model_path,
            device="cuda",
            compute_type='int8')`

Let me know if it works for you.

**Comment by aruiplex** [comment]
@jiezi4ai YOU ARE THE HERO BRO.
