### ISSUE TITLE
Add option to only align text to audio

### ISSUE THREAD

**Issue by LoggeL** [m-bain/whisperX#36]
Would be nice, if there was a flag to pass a srt or other text file directly to the alignment, skipping the text recognition. 
E.g. sometimes I already have a ground truth transcription and I only want to align it to the audio.
Is this possible?

**Comment by m-bain** [comment]
Currently the CLI does not support this but you could definitely use the python package as follows:

```python
import whisperx

device = "cuda" 
audio_file = "audio.mp3"
language="en"
# load alignment model and metadata
model_a, metadata = whisperx.load_align_model(language_code=language, device=device)

# assume result_segments are already known
# gt_transcription = [{"text": "Hi, this is jane", "start": 0.41, "end": 2.43}, ...]

# align gt_transcription
result_aligned = whisperx.align(gt_transcription, model_a, metadata, audio_file, device)
```

You just need your ground truth transcription to be a list of dicts of each utterance with "start", "end", and "text" keys.

**Comment by LoggeL** [comment]
That's exactly what I needed 🥳
Thank you for your work on the library.

**Comment by paihengxu** [comment]
> Currently the CLI does not support this but you could definitely use the python package as follows:
> 
> ```python
> import whisperx
> 
> device = "cuda" 
> audio_file = "audio.mp3"
> language="en"
> # load alignment model and metadata
> model_a, metadata = whisperx.load_align_model(language_code=language, device=device)
> 
> # assume transcription from "audio.mp3" is already known.
> # transcription = [{"text": "Hi, this is jane", "start": 0.41, "end": 2.43}, ...]
> 
> # so we only need to do alignment, not transcription
> result_aligned = whisperx.align(transcription, model_a, metadata, audio_file, device)
> ```
> 
> You just need your pre-computed transcription to be a list of dicts of each utterance with "start", "end", and "text" keys.

Thanks for posting this! Is there any workaround if the pre-computed (or the ground-truth) transcription does not have timestamps, i.e., no "start" and "end" keys?

**Comment by m-bain** [comment]
@paihengxu  Unfortunately not right now, if it is critical to your research, I would suggest something along the following:: 

1. Split the transcript into N sentences
2. Split the audio into M chunks of 30s audio
3. For each sentence in N, calculate the alignment cost for every chunk in M
4. Perform DTW alignment over sentences and chunks. (this will assign each sentence to a 30s chunk in the audio)
5. Finally, perform whisperx alignment

If this goes well, share the code or even push. 
Good luck 😎🧙‍♂️.

**Comment by paihengxu** [comment]
Thank you for the suggestion! I don't have time to work on it, but #86 mentioned several other options for forced alignment, in case anyone is interested.
