### ISSUE TITLE
Translate like English to others Language 

### ISSUE THREAD

**Issue by kumar045** [m-bain/whisperX#37]
Currently supported only English translation
How to do translation in others Language ?

**Comment by m-bain** [comment]
this is something for whisper https://github.com/openai/whisper

**Comment by elia-ashraf** [comment]
> 

Hello. Try using:
`model.transcribe('audio.mp3, language='hi')`

or tag of whatever language you want to translate you speech to. I tried Russian to German and it worked fine for me. But it only works with large-v1 and not the newer models.
