### ISSUE TITLE
Cannot run the "Large" model

### ISSUE THREAD

**Issue by wesleyliwewa** [m-bain/whisperX#377]
Hello, I'm using whisperX with Subtitle Edit.

When choosing the model (under Audio to text), it will show "No Text Found" if I select the Large model. However, once I change to other model like Medium, it will have no problem.

I check the Error Log, and found this line:

"ValueError: Invalid model size 'large', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2"

It seems like as the Large model's name is large.pt, which is not fit either large-v1 or large-v2, so the error occurs.

Is there anyway can set or change it? (I tried to rename the file to large-v1.pt, but it did not work, it would not show up in the selection bar.)

Thank you.

**Comment by Barabazs** [comment]
Please don't open issues for other software here. You will need to request support from Subtitle Edit.
