### ISSUE TITLE
emotion detection

### ISSUE THREAD

**Issue by MyraBaba** [m-bain/whisperX#384]
Hi

Is there any way to detect emotion, stress of the speaker within the whisper domain ? 

Best

**Comment by code-switched** [comment]
> Hi
> 
> Is there any way to detect emotion, stress of the speaker within the whisper domain ?
> 
> Best

The github repo named [Whisper.cpp](https://github.com/ggerganov/whisper.cpp) has a feature called "Confidence color-coding" `--print-colors`

It can be used to highlight words with high or low confidence and that's the closest I've seen to emotion detection.

**Comment by sorgfresser** [comment]
Another way would be sentiment analysis on the transcript in a postprocessing step. Maybe have a look at BERT or newer versions for this.

**Comment by chenrq2005** [comment]
https://arxiv.org/pdf/2306.12991.pdf

https://huggingface.co/speechbrain/emotion-diarization-wavlm-large

**Comment by Barabazs** [comment]
This seems very out of scope for this project. Closing for now, unless @m-bain has a different opinion.
