### ISSUE TITLE
The "score" in the returned results represents what?

### ISSUE THREAD

**Issue by chaoqingshuai** [m-bain/whisperX#398]
{'segments': [{'start': 0.975,
   'end': 1.575,
   'text': ' Yes, sir.',
   'words': [{'word': 'Yes,', 'start': 0.975, 'end': 1.215, 'score': 0.537},
    {'word': 'sir.', 'start': 1.295, 'end': 1.575, 'score': 0.302}]},
]}

**Comment by rosyvs** [comment]
I had the same question and found this from m-bain themself:
https://github.com/m-bain/whisperX/issues/20
> word-segments now have a "score", however, this is from wav2vec2 model not whisper [d395c21](https://github.com/m-bain/whisperX/commit/d395c21b8399cb2f29643a75f91469917cdbb991)
