### ISSUE TITLE
Word timestamp

### ISSUE THREAD

**Issue by Tarifut** [m-bain/whisperX#405]
Hello
I have a strange behavior.
If a word is followed by silence, the end of the word is far from his start

EX: a 1s approx. word got a duration of 4s approx.

I think is an issue with the segment size (this word is the last of the segment)
I can get expected values with faster-whisper

**Comment by Tarifut** [comment]
sample json:

WhisperX:

`"segments": [
        {
            "start": 6.438,
            "end": 11.422,`

faster-whisper:

`"segments": [
        {
            "id": 1,
            "seek": 2962,
            "start": 6.14,
            "end": 7.44,`

**Comment by Tarifut** [comment]
UPDATE:
The issue is present on french language. I tried another align model, it's worse!
Faster whisper uses whisper for alignment i think whereas whisperX uses wav2sec.
It's maybe why i have 2 différents results.

**Comment by Tarifut** [comment]
UPDATE:
present on danish also

**Comment by Tarifut** [comment]
Problem solved

**Comment by Tarifut** [comment]
I just changed the align model.
Much better results

**Comment by arlovibre** [comment]
> For the moment, I only use the HUBERT_XLARGE model for all languages.

How can I use this model? And have you found a better one, or are you using the same thing still?

**Comment by Koowah** [comment]
Very interested in how to achieve this also. I have the same issue (for the french language)
