### ISSUE TITLE
Please help me !!!! RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by yaospacetim** [m-bain/whisperX#410]
I followed the usage in readme, but it still have the bug of this:
----------------------------------------------------------------------------------------
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Downloading (…)08837e8b/config.json: 100%|████████████████████████████████████████████████| 2.80k/2.80k [00:00<?, ?B/s]
Downloading (…)37e8b/vocabulary.txt: 100%|██████████████████████████████████████████| 460k/460k [00:00<00:00, 1.81MB/s]
Downloading (…)37e8b/tokenizer.json: 100%|████████████████████████████████████████| 2.20M/2.20M [00:00<00:00, 4.64MB/s]
Downloading model.bin: 100%|██████████████████████████████████████████████████████| 3.09G/3.09G [04:30<00:00, 11.4MB/s]
No language specified, language will be first be detected for each audio file (increases inference time).
100%|█████████████████████████████████████| 16.9M/16.9M [00:03<00:00, 5.72MiB/s]██| 3.09G/3.09G [04:30<00:00, 11.6MB/s]
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.6. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file C:\Users\PS\.cache\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
Warning: audio is shorter than 30s, language detection may be inaccurate.
Detected language: zh (0.99) in first 30s of audio...
Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_large_lv60k_asr_ls960.pth" to C:\Users\PS/.cache\torch\hub\checkpoints\wav2vec2_fairseq_large_lv60k_asr_ls960.pth
100%|████████████████████████████████████████████████████████████████████████████▋| 1.17G/1.18G [01:49<00:00, 11.5MB/s]
Traceback (most recent call last):
  File "\\?\C:\Users\PS\miniconda3\envs\whisperx\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
  File "c:\llm_collected\whisperx\whisperx\transcribe.py", line 172, in cli
    align_model, align_metadata = load_align_model(align_language, device, model_name=align_model)
  File "c:\llm_collected\whisperx\whisperx\alignment.py", line 70, in load_align_model
    align_model = bundle.get_model(dl_kwargs={"model_dir": model_dir}).to(device)
  File "C:\Users\PS\miniconda3\envs\whisperx\lib\site-packages\torchaudio\pipelines\_wav2vec2\impl.py", line 126, in get_model
    model.load_state_dict(self._get_state_dict(dl_kwargs))
  File "C:\Users\PS\miniconda3\envs\whisperx\lib\site-packages\torchaudio\pipelines\_wav2vec2\impl.py", line 202, in _get_state_dict
    state_dict = super()._get_state_dict(dl_kwargs)
  File "C:\Users\PS\miniconda3\envs\whisperx\lib\site-packages\torchaudio\pipelines\_wav2vec2\impl.py", line 89, in _get_state_dict
    state_dict = load_state_dict_from_url(url, **dl_kwargs)
  File "C:\Users\PS\miniconda3\envs\whisperx\lib\site-packages\torch\hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\Users\PS\miniconda3\envs\whisperx\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\PS\miniconda3\envs\whisperx\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by yaospacetim** [comment]
I don't know how to fix it

**Comment by Haulyn5** [comment]
I encountered the same error. It appears the issue might be a corrupted model file, possibly due to a canceled download or network issues.

I resolved this by removing the model file using the command: 

```
rm ~/.cache/torch/hub/checkpoints/wav2vec2_fairseq_base_ls960_asr_ls960.pth
```

Then, I fixed the network issues and ran `whisperx` again. The `whisperx` just downloaded more models and the problem was fixed.

**Comment by chrisbward** [comment]
> I encountered the same error. It appears the issue might be a corrupted model file, possibly due to a canceled download or network issues.
> 
> I resolved this by removing the model file using the command:
> 
> ```
> rm ~/.cache/torch/hub/checkpoints/wav2vec2_fairseq_base_ls960_asr_ls960.pth
> ```
> 
> Then, I fixed the network issues and ran `whisperx` again. The `whisperx` just downloaded more models and the problem was fixed.

This, but also;

```
cd ~/.cache/torch/hub/checkpoints/
wget -c https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth
```
