### ISSUE TITLE
vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}

### ISSUE THREAD

**Issue by soberupkg** [m-bain/whisperX#433]
vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset},Hello, the test parameters are not effective, please help to check。
model = whisperx.load_model("/data/model/"+model_path, device, compute_type=compute_type, asr_options={"condition_on_previous_text": True,"initial_prompt":'hi'},vad_options={"vad_onset": 0.001, "vad_offset": 0.001})

![image](https://github.com/m-bain/whisperX/assets/142582701/a4ffaa85-6b99-4fe9-bdd5-11222ca2e90a)
Vad caused here, no voice detected,Although I set {"vad_onset": 0.001, "vad_offset": 0.001}, it does not take effect
You can adjust  {"vad_onset": 0.001, "vad_offset": 0.001} to   model.transcribe(audio, batch_size=batch_size, language='es', vad_options={"vad_onset": 0.001, "vad_offset": 0.001})，Of course, this is just a suggestion. You can modify it according to your project plan

**Comment by soberupkg** [comment]
model = whisperx.load_model("/data/model/"+model_path, device, compute_type=compute_type, asr_options={"condition_on_previous_text": True,"initial_prompt":'hi'},vad_options={"vad_onset": 0.001, "vad_offset": 0.001})

**Comment by crisprin17** [comment]
@soberupkg Not sure I understand your message, but I am also not seeing a difference when I change these parameters. Did you figure out why?

**Comment by soberupkg** [comment]
@

**Comment by soberupkg** [comment]
> @soberupkg Not sure I understand your message, but I am also not seeing a difference when I change these parameters. Did you figure out why?

https://qpt-dev-voices-1251626569.cos.ap-beijing.myqcloud.com/A10/test2.wav
You can test it with this audio

**Comment by soberupkg** [comment]
> @soberupkg Not sure I understand your message, but I am also not seeing a difference when I change these parameters. Did you figure out why?

You can test it with this audio
https://qpt-dev-voices-1251626569.cos.ap-beijing.myqcloud.com/A10/spa-4346.wav

**Comment by soberupkg** [comment]
@crisprin17 
You can test it with this audio
https://qpt-dev-voices-1251626569.cos.ap-beijing.myqcloud.com/A10/spa-4346.wav
