### ISSUE TITLE
Is there a possibility to pre download model.bin?

### ISSUE THREAD

**Issue by vyk12** [m-bain/whisperX#434]
Hi there,
To reduce cost, we launch a new Docker instance of whisperx for speech-to-text when an audio file needs to be handled. The problem is that each time we launch a new instance a run the model for the first time, it downloads a file (model.bin) which weighs ~3 GB, which can take a few minutes depending on the connection.
Is there anywhere I can find this model.bin file to put it in my docker image, and tell whisperx to use it instead of downloading it? (I have a python script that uses the whisperx lib)
Thanks!

**Comment by chaoqingshuai** [comment]
You can replace the name of the model with the path of the local model。

for example:

whisperx.load_model("/data/models/faster-whisper-medium.en", device, compute_type=compute_type)

**Comment by victor-upmeet** [comment]
Thank you for your help. I ended up adding these 2 lines in my Dockerfile:

```
RUN mkdir /usr/bin/fast-whisper-large-v2
RUN wget -O /usr/bin/fast-whisper-large-v2/model.bin https://huggingface.co/guillaumekln/faster-whisper-large-v2/resolve/main/model.bin
```

And updating my Python call as @chaoqingshuai suggested:

`whisperx.load_model("/usr/bin/fast-whisper-large-v2/model.bin", device, compute_type=compute_type)`

**Comment by vyk12** [comment]
Thank you for your help. I ended up adding these lines in my Dockerfile:

```
RUN mkdir /usr/bin/fast-whisper-large-v2

RUN wget -O /usr/bin/fast-whisper-large-v2/config.json https://huggingface.co/guillaumekln/faster-whisper-large-v2/resolve/main/config.json
RUN wget -O /usr/bin/fast-whisper-large-v2/model.bin https://huggingface.co/guillaumekln/faster-whisper-large-v2/resolve/main/model.bin
RUN wget -O /usr/bin/fast-whisper-large-v2/tokenizer.json https://huggingface.co/guillaumekln/faster-whisper-large-v2/resolve/main/tokenizer.json
RUN wget -O /usr/bin/fast-whisper-large-v2/vocabulary.txt https://huggingface.co/guillaumekln/faster-whisper-large-v2/resolve/main/vocabulary.txt
```

And updating my Python call as @chaoqingshuai suggested:

`whisperx.load_model("/usr/bin/fast-whisper-large-v2", device, compute_type=compute_type)`

**Comment by mfernandezsidn** [comment]
And for v3 model?

**Comment by fredericky123** [comment]
> the solution

https://pyvideotrans.com/model
