### ISSUE TITLE
subs are way, way too long 

### ISSUE THREAD

**Issue by jkkma** [m-bain/whisperX#441]
Hello, when i use this command:
whisperx --hf_token mytoken --model large-v2 --align_model WAV2VEC2_ASR_LARGE_LV60K_960H --language ja --task translate --output_format srt --device cuda --batch_size 16 --compute_type float16 coolarino.mp3
I get subs that are way too long like in the image
![Screenshot 2023-08-28 011147](https://github.com/m-bain/whisperX/assets/16640398/6a126e98-eb05-41b1-a34f-14c095a0702a)

**Comment by jim60105** [comment]
A new argument `--chunk_size` has been added at #445.
Please check if this resolves your issue.

**Comment by jkkma** [comment]
![Screenshot 2023-09-05 190250](https://github.com/m-bain/whisperX/assets/16640398/40c36237-66b0-42f7-9efd-ea6ed2390b18)
Now thats a huge difference, thank you. I'll close the issue.
