### ISSUE TITLE
Is there a function within WhisperX that can generate an SRT file?

### ISSUE THREAD

**Issue by bmox** [m-bain/whisperX#45]
Is there a function within WhisperX that can generate an SRT file?

**Comment by MahmoudAshraf97** [comment]
CLI usage already generates word-level and segment-level SRT files, for python usage you can use the write_srt function here
https://github.com/m-bain/whisperX/blob/5b8c8a7bd39eff6715a3a3a0498d7774f832d205/whisperx/utils.py#L73-L97
