### ISSUE TITLE
output with no speaker

### ISSUE THREAD

**Issue by remic33** [m-bain/whisperX#460]
It happened to me that I got output with no speaker mentioned. Is it regular? 
Example output element : 
{'start': 819.734, 'end': 820.755, 'text': 'Avec un voisin.', 'words': [{'word': 'Avec', 'start': 819.734, 'end': 820.294, 'score': 0.54}, {'word': 'un', 'start': 820.354, 'end': 820.454, 'score': 0.646}, {'word': 'voisin.', 'start': 820.474, 'end': 820.695, 'score': 0.294}]}

**Comment by Barabazs** [comment]
Closing since this is an old issue. Please feel free to reopen if the issue is still relevant.
