### ISSUE TITLE
Which one is better ? (MFA vs WhisperX)

### ISSUE THREAD

**Issue by Madhavan0123** [m-bain/whisperX#461]

**Comment by ch826** [comment]
What does MFA stand for and where can a person find out more about it?

**Comment by OrhanAgaOglu** [comment]
ontreal forced alignment

**Comment by OrhanAgaOglu** [comment]
> What does MFA stand for and where can a person find out more about it?

Montreal Forced Alignment

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
Well, can WhisperX get the timestamps of phonemes too? Not just word level forced alignment
