### ISSUE TITLE
whisperX is not as accurate as faster-whisper for songs, what's the reason?

### ISSUE THREAD

**Issue by pxEkin** [m-bain/whisperX#465]
whisperX implements batch processing based on faster-whisper, why the two results are different? [Both use large-v2].
 faster-whisper and whisper have the same results.

audio file:
[song-64k.zip](https://github.com/m-bain/whisperX/files/12549530/song-64k.zip)

whisperX results:
![image](https://github.com/m-bain/whisperX/assets/40013733/7f6c2ca6-164e-4b10-85a4-aae3824bb9fb)

faster-whisper results:
![image](https://github.com/m-bain/whisperX/assets/40013733/49a46612-8644-49d0-85a6-723c0398ac2b)

**Comment by awerks** [comment]
in faster_whisper, the detected language is Chinese, which is not right. What's the detected language in WhisperX? The difference in detected languages could make a difference

**Comment by pxEkin** [comment]
> in faster_whisper, the detected language is Chinese, which is not right. What's the detected language in WhisperX? The difference in detected languages could make a difference

whisperX test command line：whisperx ./audio/song-64k.aac --model large-v2 --batch_size 4 --language en --output_dir ./audio/.   in the tset  i specified English, If no language is specified， the detected language is zh in whisperX.    
![image](https://github.com/m-bain/whisperX/assets/40013733/0c444810-af09-41af-a89f-11e02aba5b18)

**Comment by alvimu** [comment]
Hi,

Is it possible print the transcription while the audio is playing?

**Comment by jkukul** [comment]
Missing words for this songs are caused by the VAD filter applied by whisperX. VAD filter recognises some parts of the songs as not speech, probably because of the background musing. faster-whisper doesn't apply any VAD filtering by default. 

To get all words for this particular song, run whisperX with more loose VAD settings, e.g. `--vad_onset 0.10 --vad_offset 0.05`.

**Comment by pxEkin** [comment]
> Missing words for this songs are caused by the VAD filter applied by whisperX. VAD filter recognises some parts of the songs as not speech, probably because of the background musing. faster-whisper doesn't apply any VAD filtering by default.
> 
> To get all words for this particular song, run whisperX with more loose VAD settings, e.g. `--vad_onset 0.10 --vad_offset 0.05`.

Yes, that is indeed the reason, I will close this issue

**Comment by dreamshit** [comment]
saved my day
