### ISSUE TITLE
The result is different  with execute multiple times

### ISSUE THREAD

**Issue by ToBigboss** [m-bain/whisperX#47]
1.command：
whisperx ./audio/diff-result-times.mp4 --align_model WAV2VEC2_ASR_LARGE_LV60K_960H --output_dir ./audio/ --language en --model small.en

2.audio：

https://user-images.githubusercontent.com/40013733/215309350-d86e8d45-9b83-4a32-a21f-b32e979680b6.mp4

3.different results, for example：
![image](https://user-images.githubusercontent.com/40013733/215309407-82650668-060e-4c8c-b237-891a87e80177.png)

**Comment by arnavmehta7** [comment]
This is something that is inherent in whisper. It generally comes when the audio lacks words or is at ends. Halluciations are inherent to whisper.

**Comment by arnavmehta7** [comment]
Also setting a fixed seed could help in this.
