### ISSUE TITLE
whisperx error after upgrade

### ISSUE THREAD

**Issue by iAladeen** [m-bain/whisperX#480]
whisperx was working fine, idk why i tried to upgrade it by pip install git+https://github.com/m-bain/whisperx.git --upgrade

now it gives the following error
Help would be appreciated

C:\Users\nouma\OneDrive\Desktop\test>whisperx "2 - Copy.mp4" --device cuda --model large-v2 --output_format srt --task translate
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
No language specified, language will be first be detected for each audio file (increases inference time).
Traceback (most recent call last):
  File "C:\Users\nouma\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nouma\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nouma\AppData\Local\Programs\Python\Python310\Scripts\whisperx.exe\__main__.py", line 7, in <module>
  File "C:\Users\nouma\AppData\Local\Programs\Python\Python310\lib\site-packages\whisperx\transcribe.py", line 149, in cli
    model = load_model(model_name, device=device, device_index=device_index, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task)
  File "C:\Users\nouma\AppData\Local\Programs\Python\Python310\lib\site-packages\whisperx\asr.py", line 75, in load_model
    default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
TypeError: TranscriptionOptions.__new__() missing 3 required positional arguments: 'repetition_penalty', 'no_repeat_ngram_size', and 'prompt_reset_on_temperature'

**Comment by triinity2221** [comment]
@iAladeen - it happened to me in a recent update due to incompatibility from the faster-whisper package, but soon it was fixed though as mentioned here in this [issue](https://github.com/m-bain/whisperX/issues/457). Check the version of whisperx you have installed once.

**Comment by iAladeen** [comment]
> @iAladeen - it happened to me in a recent update due to incompatibility from the faster-whisper package, but soon it was fixed though as mentioned here in this [issue](https://github.com/m-bain/whisperX/issues/457). Check the version of whisperx you have installed once.

Thanks you, it worked

**Comment by iAladeen** [comment]
> @iAladeen - it happened to me in a recent update due to incompatibility from the faster-whisper package, but soon it was fixed though as mentioned here in this [issue](https://github.com/m-bain/whisperX/issues/457). Check the version of whisperx you have installed once.

Thankyou, it worked.
