### ISSUE TITLE
what does the batch size mean

### ISSUE THREAD

**Issue by BaohaoLiao** [m-bain/whisperX#482]
Hi, 

I'm new to whisperX and want to use it for ASR, especially for batching inference. 

I see this example from the main page:
```
audio_file = "audio.mp3"
batch_size = 16 
audio = whisperx.load_audio(audio_file)
result = model.transcribe(audio, batch_size=batch_size)
```
This makes me confused, since there is only one audio file but you set the batch size as 16. Is there any difference between the conventional batch size and the batch size here? 

In addition, is it possible for me to do batching inference? I.e. transcribe multiple audios at the same time. If it is possible, could you direct me to some examples?

**Comment by CaRniFeXeR** [comment]
The audio file is split into n segments of up to 30s each. The batchsize references to the number of segments that are forward passed in parallel.  See https://arxiv.org/pdf/2303.00747.pdf for more details-

You could concatenate your audio files into one to describe multiple files at once.

**Comment by BaohaoLiao** [comment]
I see. Thank you

**Comment by haiderasad** [comment]
@CaRniFeXeR is whisX faster than faster whisper ?if so then how do you guys achieve this in regards to batching

**Comment by joiemoie** [comment]
> The audio file is split into n segments of up to 30s each. The batchsize references to the number of segments that are forward passed in parallel. See https://arxiv.org/pdf/2303.00747.pdf for more details-
> 
> You could concatenate your audio files into one to describe multiple files at once.

If you concatenate, and have auto detect language, would it redetect language for each segment? Or use the same language the whole way through
