### ISSUE TITLE
audio split into 30-sec chunks. What does it mean?

### ISSUE THREAD

**Issue by Karoljv** [m-bain/whisperX#484]
I have a question about 30-sec chunks. What if speech lasts more than 30 sec? For example, the audio is 50 sec long. Speaker 1 pronounce "discovery" between 29 sec to 31 sec :
Speaker 1: I have a discovery land rover.

I can see that whisperX deals with it nicely and I have not actually seen this going wrong? But how the word "discovery" is not cutted in half if whisper is limited to 30 sec chunks. Is it related to heuristic sliding window or some other algorithm?

Thanks for sharing repo. Great work :)

**Comment by CaRniFeXeR** [comment]
The 30-sec is an upper bound. So in your case the cut would be made before "discovery".
