### ISSUE TITLE
Where is word-level srt file？

### ISSUE THREAD

**Issue by ToBigboss** [m-bain/whisperX#5]

**Comment by RaulKite** [comment]
It dissapears in this commit: 
https://github.com/m-bain/whisperX/commit/645d55903aefe481e8a8fb68415c95516c9c9958?diff=split#diff-39c4b5d11415296340281baacd8c765e49483b736c55144053c2aadfc90a3767


 {"segments": word_level} is no longer returned in align function

**Comment by ToBigboss** [comment]
> It dissapears in this commit: [645d559?diff=split#diff-39c4b5d11415296340281baacd8c765e49483b736c55144053c2aadfc90a3767](https://github.com/m-bain/whisperX/commit/645d55903aefe481e8a8fb68415c95516c9c9958?diff=split#diff-39c4b5d11415296340281baacd8c765e49483b736c55144053c2aadfc90a3767)
> 
> {"segments": word_level} is no longer returned in align function

got it

**Comment by RaulKite** [comment]
Any quick fix?

**Comment by m-bain** [comment]
Ok it's back https://github.com/m-bain/whisperX/commit/228b857597488ab7c705bd5ad680818dee769dbd
Some words are never aligned so when this happens they are merged with neighbouring words that do have timestamp.
You can drop these words with `--drop_non_aligned` flag.

**Comment by RaulKite** [comment]
Thank you very much 🙏
