### ISSUE TITLE
OOM && Large GPU usage

### ISSUE THREAD

**Issue by arnavmehta7** [m-bain/whisperX#50]
Hi, I am using this, but it doesn't seems to release the gpu vram. I am using large-v2 model and it's using 16gigs of GPU ram. Which I don't think is NORMAL at all, moreover it doesn't free up the ram. Is this normal?

**Comment by m-bain** [comment]
Memory scales with length of input segment to wav2vec2 model. With current version, adding
--vad_filter
Ensures that no segments greater than 30s are inputted to the w2v model. You can further reduce gpu reqs by
a. Using smaller w2v align_model  
b. Limit input segment duration

I will add b as a new feature at some point

**Comment by arnavmehta7** [comment]
I am using a older commit, and its now using 28gigs of GPU ram, which is TOOOO much. Any idea how to fix this?

**Comment by arnavmehta7** [comment]
Files are being processed in a loop, and seems like after every file, GPU ram usage pops up by ~2gbs ram.

**Comment by arnavmehta7** [comment]
@m-bain I just ran a very long audio and it showed that it tried to allocate 30gbs of GPU ram, is there any clean fast fix?
Thankyou!

**Comment by arnavmehta7** [comment]
@m-bain Sorry to msg a lot, but can you please confirm me if the `align` function also segments the audio segment - 30 seconds - to prevent the OOM error while aligning? Or that is only limited to VAD?

**Comment by mustafa0x** [comment]
@arnavmehta7 I'm running into this issue as well. Did you find a fix?
