### ISSUE TITLE
importing whisperx - no module named 'lightning_fabric.utilities'

### ISSUE THREAD

**Issue by CMoranoA** [m-bain/whisperX#500]
Hi, hope everybody is doing well!

I am having some trouble importing the module using colab. Actually I am pip installing...

!pip install git+https://github.com/m-bain/whisperx.git
!pip install git+https://github.com/m-bain/whisperx.git --upgrade
!pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.0 --index-url https://download.pytorch.org/whl/cu117
!pip install openai
!pip install pdfkit
!pip install pydub
!pip install python-docx
!pip install pypandoc
!apt-get install -y wkhtmltopdf

but when loading the module, the following error...

ModuleNotFoundError: No module named 'lightning_fabric.utilities'

Strange since today this was not happening. Some ideas?

Than you all.

**Comment by Barabazs** [comment]
This seems unrelated to whisperx as lightning_fabric is not used here.
