### ISSUE TITLE
Disfluencies

### ISSUE THREAD

**Issue by darkzbaron** [m-bain/whisperX#505]
Any plan to detect disfluencies, hesitation, fillers? That would be awesome

**Comment by m-bain** [comment]
See here, you might have to play around with custom prompt depending on what you are looking for https://github.com/m-bain/whisperX/issues/293

**Comment by darkzbaron** [comment]
I think this repo does it, I need to check what method they use. Thanks anyway! https://github.com/linto-ai/whisper-timestamped
