### ISSUE TITLE
Error when adding torch, and also how to add --diarize/parameters when using python

### ISSUE THREAD

**Issue by Dec1lent** [m-bain/whisperX#52]
I have cloned WhisperX and I'm getting a syntax error, about getting torch 1.8. But it seems like there is a syntax at error  "torch (>=1.8.)" when ran, it should probably be replaced with "torch >=1.8.0" or "torch >=1.8,<1.9" if torch 1.9 also works.

`epkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS - torch (>=1.8.*)`

I'm also interested in learning how to add parameters in python.

**Comment by spullara** [comment]
This happens for me as well. Why was the issue closed?
