### ISSUE TITLE
Bad things might happen unless you revert pyannote.audio to 0.x.

### ISSUE THREAD

**Issue by manjunath7472** [m-bain/whisperX#546]
Getting this warning message.

Warning message
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu118. Bad things might happen unless you revert torch to 1.x

is that ok?

Is there a problem if model can be trained using  pyannote.audio 3.0.1?? 
Will diarization would be much better than now?

**Comment by sorgfresser** [comment]
That is very okay, see #258 

There are new models available for 3.0.1 though, so we could think of using v3 for diarization @m-bain 
I could PR that if you'd like me to.

**Comment by manjunath7472** [comment]
Yep its already using v3, Ok ignoring then..

**Comment by eye4got** [comment]
None of the following code seems to silence the warning. Is there any easy way to silence it, it's incredibly verbose and I typically using the INFO level when running my scripts

```
logging.getLogger("pyannote").setLevel(logging.ERROR)
logging.getLogger("pytorch").setLevel(logging.ERROR)
logging.getLogger("speechbrain").setLevel(logging.ERROR)
warnings.filterwarnings("ignore")
```
