### ISSUE TITLE
Model was trained with pyannote 0.0.1 warning even though I am running the most recent version

### ISSUE THREAD

**Issue by Vilhelm-Ian** [m-bain/whisperX#557]
Model was trained with pyannote 0.0.1 warning even though I am running the most recent version.

I cloned the repo and installed whisperx using pip. I checked setup.pyp installs pyannote 3.0.0 or 3.0.1 but when I run whisper x I get the above warning

**Comment by sorgfresser** [comment]
Dupe #546

**Comment by manjunath7472** [comment]
Ignore..
