### ISSUE TITLE
'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by muellerelias** [m-bain/whisperX#562]
I try to use WhisperX in a clean Docker with the newest verion.
But i get the following error:

```
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
 AttributeError: 'NoneType' object has no attribute 'to'
```

Is there any problem with the pyannote.audio version?

**Comment by popoago** [comment]
your model didn't load. You need to specify an auth_token. You can follow the documentation https://github.com/m-bain/whisperX#speaker-diarization

**Comment by muellerelias** [comment]
Oh no, somehow I didn't accept the terms of the one model.
It would be cool if huggingface had an API where you could send the token and the model names and get a response as to whether you have access. This would also allow you to receive better error messages.
