### ISSUE TITLE
ValueError: This CTranslate2 package was not compiled with CUDA support

### ISSUE THREAD

**Issue by silverget** [m-bain/whisperX#575]
Hi ! 
I get this error when I run the python code on a macbook pro M1 Silicone, do you know how could I solve this?

Traceback (most recent call last):
  File "/main.py", line 38, in <module>
    model = whisperx.load_model("large-v2", "cuda", compute_type=compute_type)
  File "/lib/python3.10/site-packages/whisperx/asr.py", line 52, in load_model
    model = WhisperModel(whisper_arch,
  File "/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 128, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: This CTranslate2 package was not compiled with CUDA support

Thank you!

**Comment by DinoZoidDev** [comment]
MacBook Pro's do not have NVIDIA GPUs. CUDA cores are exclusive to machines that run NVIDIA graphics cards. You will have to switch the whisperX device to "cpu".

replace this line:
`model = whisperx.load_model("large-v2", "cuda", compute_type=compute_type)`

with this line:
`model = whisperx.load_model("large-v2", "cpu", compute_type=compute_type)`
