### ISSUE TITLE
Can someone help me? I've encountered an error that I can't resolve.

### ISSUE THREAD

**Issue by maxoo1001** [m-bain/whisperX#587]
# When I was separating vocals using whisperX, I encountered an error. Even though I printed out min_speaker and tried adding this parameter, I couldn't resolve the issue. I've been troubled by this for an entire day and still can't find a solution.
`
import whisperx
import gc 

device = "cuda" 
audio_file = "D:\\Code\\whisperx\\data\\1.mp3"
batch_size = 16 # reduce if low on GPU mem
compute_type = "float16" # change to "int8" if low on GPU mem (may reduce accuracy)
local_model_path = "D:\\Code\\whisperx\\models\\large-v3\\"

model = whisperx.load_model(local_model_path, device, compute_type=compute_type)

audio = whisperx.load_audio(audio_file)
result = model.transcribe(audio, batch_size=batch_size)
print(result["segments"]) # before alignment

local_pyannote_path = ".\\models\\pyannote\\config.yaml"
diarize_model = whisperx.DiarizationPipeline(model_name=local_pyannote_path, device=device)

diarize_segments = diarize_model(audio)

result = whisperx.assign_word_speakers(diarize_segments, result)
print(diarize_segments)
print(result["segments"]) # segments are now assigned speaker IDs
 `

`Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint D:\Code\faster-whisper-GUI-main\models\pyannote\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "d:\Code\whisperx\test.py", line 71, in <module>
    diarize_segments = diarize_model(audio)
  File "d:\Code\whisperx\whisperx\diarize.py", line 29, in __call__
    segments = self.model(audio_data, min_speakers=min_speakers, max_speakers=max_speakers)
  File "D:\conda_env\envs\fastgui\lib\site-packages\pyannote\audio\core\pipeline.py", line 323, in __call__
    return self.apply(file, **kwargs)
TypeError: VoiceActivityDetection.apply() got an unexpected keyword argument 'min_speakers'`

**Comment by m-bain** [comment]
try upgrading your pyannote version to 3.1

**Comment by maxoo1001** [comment]
The pyannote's YAML file was not written correctly, causing a model to be missing, but it has been resolved.
