### ISSUE TITLE
Diarize: Everything assigned to Speaker 01

### ISSUE THREAD

**Issue by mwallinger-tu** [m-bain/whisperX#592]
I am currently transcribing and diarizing a set of 1-on-1 interviews. In the diarized transcripts everything is assigned to Speaker_01. 

whisperx p3_audio.aac --model large-v2 --diarize --min_speakers 2 --max_speakers 2 --batch_size 4 --hf_token TOKEN --language en

**Comment by vladgrand2** [comment]
I also noticed that in pyannote.diarazation 3.1 all speakers go to one person. So edit diarize.py and set **model_name="pyannote/speaker-diarization-3.0"** instead of **model_name="pyannote/speaker-diarization-3.1"**

**Comment by mwallinger-tu** [comment]
Thanks. That resolved the issues

**Comment by rrfaria** [comment]
Perhaps it is related to it 
![image](https://github.com/m-bain/whisperX/assets/11916455/c3c7c861-f694-47c0-b96b-346e8a93c0dd)

**Comment by omarsiddiqi224** [comment]
I am also running into that error. Unfortunately changing the model_name="pyannote/speaker-diarization-3.1" to model_name="pyannote/speaker-diarization-3.0" in diarize.py did not help. do you know how I can solve this?

**Comment by santialferez** [comment]
Hi, I think you also need to update to pyannote v3.1.1 to fix the problem
