### ISSUE TITLE
Diarized transcription in .txt file?

### ISSUE THREAD

**Issue by mattiaswickberg** [m-bain/whisperX#63]
The diarize version just puts the audio in an .ass file atm as far as I can see - is it possible in the current version to get the diarized output in a txt file?

Been trying this out with KBLab/wav2vec2-large-voxrex-swedish for Swedish, and while I lack the hardware for extensive testing atm, it seems to be working fine.

**Comment by nicobatalla** [comment]
Hey, I was looking for issues regarding this and found yours.

How did you fix this? I´m not able to get diarized output in txt, but it works fine when I look at the other outputs
