### ISSUE TITLE
Argument --model_dir doesn't work

### ISSUE THREAD

**Issue by EurFelux** [m-bain/whisperX#638]
I found `--model_dir` doesn't work at all. 

Actually `download_root` is not applied when loading model.
https://github.com/m-bain/whisperX/blob/8540ff5985fceee764acbed94f656063d7f56540/whisperx/transcribe.py#L169C6-L169C6

Is this designed to avoid some potential problems or just a bug? Could I add the argument?

**Comment by Barabazs** [comment]
Seems like this is resolved in the linked PR.
Please reopen if it still applies.
