### ISSUE TITLE
How could I load the local model

### ISSUE THREAD

**Issue by yumianhuli1** [m-bain/whisperX#650]
I use this command： whisperx --model './large-v3' --language de .\test.wav

But got : huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: './large-v3'.

How could I fix this?
Thanks！

**Comment by afsara-ben** [comment]
write whisperx --model large-v3 --language de .\test.wav
if it doesnt work go to https://hf.co/settings/tokens to generate a token and use it in hf_token or in 'YOUR_AUTH_TOKEN'

**Comment by yumianhuli1** [comment]
> write whisperx --model large-v3 --language de .\test.wav if it doesnt work go to https://hf.co/settings/tokens to generate a token and use it in hf_token or in 'YOUR_AUTH_TOKEN'

thanks
