### ISSUE TITLE
Low Accuracy on German

### ISSUE THREAD

**Issue by MaxS1996** [m-bain/whisperX#66]
I wanted to use WhisperX to do forced alignment on the Mozilla Common Voice German Dataset, but the words are often cut of or the segments do not align at all.

Additionally, some audio tracks are recognized as Farsi instead of German.

Is it because of the short duration of these clips (< 2-5 seconds, each)?
And how can I improve this accuracy?

Is the accuracy of the english models (for english audio) better?

**Comment by m-bain** [comment]
are you passing in `--language de`, that way it knows it is german?

**Comment by MaxS1996** [comment]
I am using the Python API (```result = model.transcribe(audio_file)```) and was not aware of a parameter for the transcribe function, that allowed me to enforce a certain language.

I was able to improve the performance to a usable level by adding the ```extend_duration``` parameter with 0.1 as value, but it still cuts of the beginning of the word from time to time

**Comment by autonompost** [comment]
@MaxS1996 How did you solve the problem with "Umlaute"?

**Comment by m-bain** [comment]
new VAD filtering feature should fix this, feel free to re-open if not
