### ISSUE TITLE
pyannote.audio use guarded in code but not setup

### ISSUE THREAD

**Issue by jmward01** [m-bain/whisperX#67]
pyannote.audio brings some great features but it is rightfully guarded in code since it requires additional credentials. Additionally it appears to be currently incompatible with the newest macs meaning install fails when it is included. The recommendation here would be to have the additional features it brings be an extra instead of part of the default install. Maybe just add:

#added to the setup() call in setup.py
#additionally, it should be removed from the requirements.txt
#I've never been good at naming things.
extras_require={"pyannote": ["pyannote.audio"]},

alternatively, the code can remove it from the  setup entirely and detect, and gracefully handle, if it isn't installed when VAD and diarization are called. This may be preferred since decoupling the diarization/vad implementation could be useful in the future when there are multiple valid options.

**Comment by m-bain** [comment]
current setup requires VAD model (however uses local model not credentials) so should be fine. Without VAD the pipeline was prone to failures
