### ISSUE TITLE
will it support whisper large-v3?

### ISSUE THREAD

**Issue by MengHao666** [m-bain/whisperX#679]

**Comment by CuriouslyCory** [comment]
I passed `--model large-v3` and it did appear to accept it as an option.

**Comment by Eie1** [comment]
> I passed `--model large-v3` and it did appear to accept it as an option.

dear friend，could I ask how you install and use large-v3，thanks a lot

**Comment by MengHao666** [comment]
> I passed `--model large-v3` and it did appear to accept it as an option.

I finally found whisper large v3 could naturally return timestamps. you can check [here](https://huggingface.co/openai/whisper-large-v3). I am uising the model as the example code there.
