### ISSUE TITLE
Working with the new VAD Feature

### ISSUE THREAD

**Issue by bballboy8** [m-bain/whisperX#68]
I'm currently trying to work with the new VAD feature but I'm getting the following error:

`TypeError: transcribe_with_vad() missing 1 required positional argument: 'vad_pipeline'`

Is there sample code anywhere for transcribing with vad?

**Comment by kanjieater** [comment]
I'm also hoping for some example code for this feature.

**Comment by Barabazs** [comment]
You'll need this function https://github.com/m-bain/whisperX/blob/f7093e60d367757e1e32a1da069d7c623455b82d/whisperx/transcribe.py#L303
And you can see how to use it in the cli function.
Most of it here: https://github.com/m-bain/whisperX/blob/f7093e60d367757e1e32a1da069d7c623455b82d/whisperx/transcribe.py#L643-L691C3

**Comment by kanjieater** [comment]
> You'll need this function
> 
> https://github.com/m-bain/whisperX/blob/f7093e60d367757e1e32a1da069d7c623455b82d/whisperx/transcribe.py#L303
> 
> 
> And you can see how to use it in the cli function.
> Most of it here:
> https://github.com/m-bain/whisperX/blob/f7093e60d367757e1e32a1da069d7c623455b82d/whisperx/transcribe.py#L643-L691

Thanks for the example. 

I think I'll hold off in importing it into some other  scripts as of right now, as it seems like you would have to pull in quite a few other pieces from the cli snippet to get that `transcribe_with_vad` working.

**Comment by m-bain** [comment]
turned on by default now
