### ISSUE TITLE
Edit the automatic transcript before the alignment?

### ISSUE THREAD

**Issue by mindofsteel** [m-bain/whisperX#69]
Hello. Thank you so much for this. It’s unbelievable!!

I was just wondering- is it possible for me to manually edit the automatic transcript (i.e., to correct any errors) before the automatic forced alignment is performed?

**Comment by MahmoudAshraf97** [comment]
It's possible in python usage, the result from whisper can be edited manually, but what is the sought benefit from this vs editing the result?

**Comment by dansommer** [comment]
Hi there! 

DOPE - Do Once Publish Everywhere :-)

If both a formatted transcript and closed captions are needed as the final deliverables/outputs, it can be very helpful to have the corrected transcript ready before moving to the alignment and segmentation steps of the creating the caption files. In this way it's not necessary to make corrections in two places. 

There are many instances where there are specific style requirements for the closed captions such as characters per lines, lines per caption frame, minimum duration, maximum duration, maximum characters per second. While WhisperX doesn't allow for those granular setting now, having the word-by-word timings allows for these possibilities in the future. If it's possible to correct the automatic transcript before forced alignment, then these stylistic preference can more easily and accurately be automated. 

Similarly, with the word-by-word timings it's possible to build functionality to create an interactive transcript in addition to the closed caption files.

https://lowerquality.com/gentle/
https://singingdiction.com/songs/podcast107.html 

It does look like this question was asked in a different way in another thread.  

https://github.com/m-bain/whisperX/issues/36

**Comment by m-bain** [comment]
I see, this would be for human-in-the-loop. This is quite outside of my expertise and its more of a specific usecase.

Definitely seems useful but I think this would require an editor UI etc, and outside of my remit :')
