### ISSUE TITLE
Isn't there a local INFERENCE file to inspect?

### ISSUE THREAD

**Issue by APISeeker** [m-bain/whisperX#695]
Hello, 
I saw that "whisperx --help" let you see all the arguments that can be used. Okay, but I want to see the code of the python script, and see the arguments there, so I can modify or add things etc? Where can I do that? Why isn't there a file locally that I can expect please?

Thxx

**Comment by Barabazs** [comment]
This question is too broad and should be posted on a python coding forum or stackoverflow type site. Closing due to off-topic
