### ISSUE TITLE
How to FORCE the model to LITERALY TRANSCRIBE the NUMBERS in the form in which it was said.

### ISSUE THREAD

**Issue by dolglao** [m-bain/whisperX#696]
Friends, I'd like some help. How can I make the model **transcribe literally what was said** without replacing it with numbers? I need to **do this without using librarys like num2words**.

Apparently in the original whisper library, it is possible: https://github.com/openai/whisper/discussions/1041

But how could I adapt it to whisperx?

Thank you all for your help.

**Comment by dolglao** [comment]
Guys, I found this and worked for me.
https://github.com/m-bain/whisperX/issues/300#issuecomment-1576411111

**Comment by dolglao** [comment]
Guys, I found this and worked for me.
https://github.com/m-bain/whisperX/issues/300#issuecomment-1576411111

**Comment by timotheecour** [comment]
instead, see https://github.com/m-bain/whisperX/pull/303 which allows passing cli options or asr_options
