### ISSUE TITLE
Unable to set a custom align model for whisperx.load_align_model using model_dir argument

### ISSUE THREAD

**Issue by rimeikis** [m-bain/whisperX#697]
I've downloaded the "voidful/wav2vec2-xlsr-multilingual-56" model from hugging face hub to my local file system and assigned its path to variable:
```
model_align_dir = "/home/user/Programming/whisperx/model_align/"
```
Then I run code along with this align_segments function:
```
def align_segments(result, device, audio):
    # Step 2: Align whisper output
    model_a, metadata = whisperx.load_align_model(model_dir=model_align, language_code=result["language"], device=device)
    result = whisperx.align(result["segments"], model_a, metadata, audio, device, return_char_alignments=False)
    return result
```
I then get an error saying "There is no default alignment model set for this language" even though the "voidful/wav2vec2-xlsr-multilingual-56" model supports it. Seems like the model_dir argument is not working. Just in case, i printed the model_align_dir value before whisperx.load_asign_model and it prints the correct path to the model folder.

**Comment by krishnareddyML** [comment]
send your custom model path under model_name attribute instead of model_dir. Following code works for me

`align_model_dir = '/home/kpmd/krishna reddy/hf_models/jonatasgrosman_wav2vec2-large-xlsr-53-english'`
`model_a, metadata = whisperx.load_align_model(model_name=align_model_dir,language_code=result["language"], device=device)
`

check alignment.py source file, as per the code when we are using custom model it is trying to load from_pretrained method from huggingface so for that we have option to send cutom dir path instead of huggingface hub model name

**Comment by pr-data-port** [comment]
I am getting this error when trying to align english model with whisperx:
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[22], line 1
----> 1 result_aligned = whisperx.align(
      2     result["segments"], 
      3     model_a, 
      4     metadata, 
      5     audio_resampled, 
      6     device, 
      7     return_char_alignments=False)

File /data/anaconda3/envs/vsep/lib/python3.9/site-packages/whisperx/alignment.py:129, in align(transcript, model, align_model_metadata, audio, device, interpolate_method, return_char_alignments, print_progress, combined_progress, preprocess)
    126 # Load align model Huggingface processor for audio feature extraction (Normalization)
    127 if preprocess and model_type == 'huggingface':
    128     processor = Wav2Vec2Processor.from_pretrained(
--> 129         DEFAULT_ALIGN_MODELS_HF[model_lang])
    131 # 1. Preprocess to keep only characters in dictionary
    132 total_segments = len(transcript)

KeyError: 'en'`

has anyone had similar issues? 
the whisperx align model I use:
`
model_a, metadata = whisperx.load_align_model(
    model_name='jonatasgrosman/wav2vec2-large-xlsr-53-english', 
    language_code=result["language"], 
    device=device)

result_aligned = whisperx.align(
    result["segments"], 
    model_a, 
    metadata, 
    audio_resampled, 
    device, 
    return_char_alignments=False)    
`
