### ISSUE TITLE
--model location and ffmpeg error

### ISSUE THREAD

**Issue by SLong97** [m-bain/whisperX#71]
Getting the following error's and wondering if anyone could provide some more insight.

`
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
`
`
The above exception was the direct cause of the following exception:
`
`
--model base: No such file or directory
`

Here is how I am executing the transcription and diarization process.

```
audio = os.fsencode("../src/Audio/WAV-CLIP-The-Big-Tech-Show_Dropbox-CEO.wav")
python = os.fsencode("/Users/{name}/Desktop/PodNotes/WhisperX/wsprxenv/Scripts/python.exe")
script = os.fsencode("/Users/{name}/Desktop/PodNotes/WhisperX/wsprxenv/Scripts/whisperx-script.py")
min_speak = os.fsencode("1")
max_speak = os.fsencode("5")

subprocess.run([python, script, audio, "--model base", "--diarize", "--min_speakers", min_speak, "--max_speakers", max_speak])
```

I am using the diarization model offline and the transcription works correctly but it seems to take issue with the model "base" only at the diarization step, I can see in cache that I have the "small.pt" model so I assume this is what is being used? When I change to "--model small" the issue remains, transcription still works fine though.

In what file can I change the location where the model is downloaded and pulled from for the transcription and diarization process?

Can I pass in a path to the model I want to use i.e. "--model {path to model}" ?

Any help would be much appreciated.

Cheers

**Comment by alexbehrens** [comment]
+1 are you on a Mac? Getting the same issue on my m1, thinking it might be an OS thing

**Comment by carljmosca** [comment]
I see where @SLong97 references offline use.  Is this documented somewhere?
