### ISSUE TITLE
WhisperX is not working after the update

### ISSUE THREAD

**Issue by SobolevskyDmitry** [m-bain/whisperX#720]
After the recent update I cant run whisperX anymore. 

CUDA definitely works in my environment. 

I got this error after `model.bin` and `tokenizer.json` downloading.
Using `nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04` as a base image. 

CUDA_VERSION:  11.8
TORCH_VERSION:  2.0.0+cu118
DEVICE:  cuda

 ```
File "/pipeline.py", line 21, in transcribe_whisperx
    model = whisperx.load_model("large-v2", device, compute_type=compute_type)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version
```

**Comment by tjx940202** [comment]
I meet the same problem.

CUDA_VERSION: 11.8
TORCH_VERSION: 2.0.0+cu118
DRIVER VERSION 450.156.00

**Comment by cleverestx** [comment]
Perhaps me as well having this issue, although the error is different and this is my first attempt at getting it to run, so it may be unrelated.. ???

![image](https://github.com/m-bain/whisperX/assets/28905253/f86fe2d7-8bd9-4f52-a8fc-a1ce8b61fd3d)

**Comment by Pikurrot** [comment]
Hi, I had basically the same problem on Windows. That's a [CTranslate2 issue](https://github.com/OpenNMT/CTranslate2/issues/1630). Their last release 4.0.0 now supports cuda 12.x, but no longer cuda 11.x. They suggested to update the cuda version. And WhisperX depends on faster-whisper which depends on CTranslate2, so there seems to be no other way.
However, I must say I still can run WhisperX with CTranslate2 4.0.0 on Linux with a cuda 11.5.

**Comment by Pikurrot** [comment]
Also, as suggested [here](https://github.com/m-bain/whisperX/issues/719#issuecomment-1962086329), it appears that renaming the file `cublas64_11.dll` to `cublas64_12.dll` already makes it work. This file is on "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin". Tough this may be a temporal fix, I don't know if this will work on the long term, or if it will cause errors elsewhere.

**Comment by AlvinAi96** [comment]
pip install ctranslate2==3.24.0, this works for cuda 11.x
Please ref: https://github.com/OpenNMT/CTranslate2/blob/master/CHANGELOG.md

**Comment by SobolevskyDmitry** [comment]
> pip install ctranslate2==3.24.0, this works for cuda 11.x Please ref: https://github.com/OpenNMT/CTranslate2/blob/master/CHANGELOG.md

Thanks a lot for your solution, it works!  ✅

**Comment by MengHao666** [comment]
> pip install ctranslate2==3.24.0, this works for cuda 11.x Please ref: https://github.com/OpenNMT/CTranslate2/blob/master/CHANGELOG.md

TypeError: TranscriptionOptions.__new__() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold'

**Comment by eashanchawla** [comment]
Could we just pip install where we pull an older version of the whisperx repository that doesn't require faster-whisper 1 (which won't force us to use CUDA 12)?
