### ISSUE TITLE
'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings

### ISSUE THREAD

**Issue by stepakuryaev** [m-bain/whisperX#723]
I'm trying to install this project, I'm using PyCharm, a Python project, python 3.10.11, cuda 11.8, torch==2.0.0, torchvision==0.15.1, torchaudio==2.0.1, pyannote/speaker-diarization@2.1, and when, after installing all these components, I try to run the project, I get the following error: "'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings" and the program crashes. What could be the problem?

**Comment by MelluChung** [comment]
I’ve encountered the same issue. 

I am able to import speechbrain directly within the environment, so the problem should not be related to speechbrain not being installed.

**Comment by lukasbirki** [comment]
Happened to me as well, I am unable to import the package using Colab!

**Comment by davidmartinrius** [comment]
Solution:
pip install -U speechbrain==0.5.16

The version 1.0.0 of speechbrain is not working well with whisperx.

**Comment by vcombey** [comment]
It also broke the last version in replicate:
https://replicate.com/victor-upmeet/whisperx
when activating speaker diarization.
Do you know when it will be updated ?

thanks 🙏
