### ISSUE TITLE
"import whisperx"

### ISSUE THREAD

**Issue by itaipee** [m-bain/whisperX#726]
First, thanks you for the effort on whisperx . 

i'm sorry if i'm doing something very stupid ,   but while i'm using whisperx with api (whisperx command)    with python i have a problem:

in python script or prompt  , the command "import whisperx"    exit with this error :
>>> import whisperx
Usage: python script.py <input_directory> <output_directory> ?format?

this looks something very basic , any idea what I'm doing wrong ?

**Comment by Barabazs** [comment]
This question is too broad and should be posted on a python coding forum or stackoverflow type site. Closing due to off-topic
