### ISSUE TITLE
Missing Words // Cut-Off in Music

### ISSUE THREAD

**Issue by BrothaM** [m-bain/whisperX#731]
Hey there, 

I am trying to transcribe songtexts for a project with Whisper / WhisperX. 
Whisper proves to be quite helpful with -v2 , but often doesn't get the right "breaks" - otherwise it's proven to be surprisingly good for this. As an addition, I wanted to use the timestamps provided by WhisperX, however, it often simply stops within the song, while Whisper continues to write down all lines. Do you have any idea how we could try to solve that? Would we need to change the VAD manually or is there anything else we can do to get it similiar to Whisper but with the additional word-based timestamps?

**Comment by ngcheeyuan** [comment]
I'll recommend using demuc to isolate the vocals first and pass it to whisper.
