### ISSUE TITLE
Hugginface Diarization Authentication Issue

### ISSUE THREAD

**Issue by vishjain** [m-bain/whisperX#751]
Keep getting this error whether I try diarization 3.0 or some other version despite accepting the user aggrements on HF - are there any fixes here: 

torchaudio.set_audio_backend("soundfile")
Could not download 'pyannote/speaker-diarization' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:
>>> Pipeline.from_pretrained('pyannote/speaker-diarization',
...                          use_auth_token=YOUR_AUTH_TOKEN)
If this still does not work, it might be because the pipeline is gated:
----

**Comment by nkilm** [comment]
`pyannote.audio` models are gated on hg.co, you have to fill a form before you download the models. After this, you should be able to download the pyannote models.
