### ISSUE TITLE
Change the color(s) of the generated .ass files

### ISSUE THREAD

**Issue by drunk-0ctopus** [m-bain/whisperX#76]
I am trying to figure out how I can change the color(s) of the subtitles for the .ass files. Some of the videos I am transcribing have colors that clash with the white/green combination, so I typically use yellow text. The only way that works at all has been to use a program like SubtitleEdit to manually find and replace all instances of the green color with another one. It would be great if I could somehow manage this at/before transcription.

**Comment by m-bain** [comment]
you can pass in the colour to the write_ass function
