### ISSUE TITLE
Audio captions (background sounds, e.g. [applause], [dog barking])

### ISSUE THREAD

**Issue by plrojek** [m-bain/whisperX#775]
Hello,
There is a way to turn on background noises detection, like [applause], [dog barking], [engine sound] etc.? 
I know that it works in OpenAI Whisper and can't get results of these in WhisperX.

**Comment by SeeknnDestroy** [comment]
Hey @plrojek could you find how?

**Comment by plrojek** [comment]
Unfortunately no.
