### ISSUE TITLE
Getting no audio found error

### ISSUE THREAD

**Issue by USAMAAI** [m-bain/whisperX#796]
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 552.22                 Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |          Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=======================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   40C    P4             16W /   55W |       0MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

torch version 2.3

![image](https://github.com/m-bain/whisperX/assets/141249197/6b8a061d-511a-4194-b39c-83b70c1f8a5a)
![image](https://github.com/m-bain/whisperX/assets/141249197/8e43eb1f-ba49-4738-8d2b-4155f878a0da)

**Comment by Chocobi-1129** [comment]
install ffmpeg
refer to https://github.com/openai/whisper?tab=readme-ov-file#setup
