### ISSUE TITLE
whisperx.load_model & default_asr_options Error in Colab

### ISSUE THREAD

**Issue by JaviXR96** [m-bain/whisperX#797]
![Captura de pantalla 2024-05-07 130716](https://github.com/m-bain/whisperX/assets/146676614/14407203-ca47-4714-bf0a-afdf8188ed3c)

**Comment by JaviXR96** [comment]
![Captura de pantalla 2024-05-07 131210](https://github.com/m-bain/whisperX/assets/146676614/15b1d02a-ae2a-4249-9c41-130101e3a530)

**Comment by SeeknnDestroy** [comment]
Can you please specify whisperx version you are using @JaviXR96?

**Comment by JaviXR96** [comment]
Hi, @SeeknnDestroy  
Thanks for your comment. 
I just fixed it by removing a line of code ( !pip install faster-whisper --upgrade ) I added earlier to fix a bug.
Thanks!
