### ISSUE TITLE
How to tune parallel_bs appropriately?

### ISSUE THREAD

**Issue by kanjieater** [m-bain/whisperX#83]
Currently the readme says:

> Batch processing: Add --vad_filter --parallel_bs [int] for transcribing long audio file in batches (only supported with VAD filtering). Replace [int] with a batch size that fits your GPU memory, e.g. --parallel_bs 16.

I have a 4070TI, and I'm unclear what the right batch size would be. 
How does parallel_bs affect the run and are there any further recommendations for tuning it?  

Generally related question (happy to split it of of this issue if needed): I noticed high CPU usage at the beginning of a WhisperX run. Should this of actually been on the GPU and affected by this parallel_bs?

**Comment by Pikauba** [comment]
> Generally related question (happy to split it of of this issue if needed): I noticed high CPU usage at the beginning of a WhisperX run. Should this of actually been on the GPU and affected by this parallel_bs?


What you observed was VAD model running on CPU. It got fixed here: [#97 ](https://github.com/m-bain/whisperX/pull/97)

**Comment by mshakirDr** [comment]
I don't have a GPU so running everything on CPU with 32 GB memory. A batch size of 16 with `-vad_filter --parallel_bs` fluctuates between 12 and 7 GB of RAM and after some time the memory starts filling up with the process having almost the same amount of memory. How to recover the unaccounted for memory? Is this a `torch` issue? (I know from `stanza`, which uses `torch` for grammatical tagging, that batch processing of text files will eat up a lot of memory but not this much.)

**Comment by m-bain** [comment]
deprecated, there were some bugs in old batch inference code (causing some ~5% accuracy drop), so I removed it until further notice until fixed
