### ISSUE TITLE
Could I Add Timestamps to My Text by WhisperX?

### ISSUE THREAD

**Issue by vick-wuwei** [m-bain/whisperX#838]
I'm using whisperX to transcribe audio, but some words are wrong. I have the correct text file so I just need to add the timestamp of the output to my text, how do I do this？

**Comment by RichardQin1** [comment]
I also have similar needs. Could you please @ me if there is a solution

**Comment by vick-wuwei** [comment]
> I also have similar needs. Could you please @ me if there is a solution

I find this: 
https://github.com/jianfch/stable-ts
