### ISSUE TITLE
Bulk Processing

### ISSUE THREAD

**Issue by Narbs1** [m-bain/whisperX#843]
Hello everyone

I want to ask whether it is possible to bulk process files with whisperX? I have done it with faster whisper, but the same commands don't work here since wildcards don't seem to be supported. Are there any ways to transcribe all files within a directory using whisperx?

Thanks in advance!

**Comment by know634** [comment]
I am doing this, with GUI.

**Comment by Barabazs** [comment]
Not natively. You'll need to write a script to do this.
