### ISSUE TITLE
How to enable diarization in python code (not terminal)?

### ISSUE THREAD

**Issue by imc-db** [m-bain/whisperX#858]
I don't find any possibility to enable diarization from python code? Any help would be really appreciated.

`model = whisper.load_model(model_whisper, device=device, diarize=True)`
`# ---> TypeError: load_model() got an unexpected keyword argument 'diarize'`

`model = whisper.load_model(model_whisper, device=device)`

Same happens if I add this parameter to transcribe(...)

`result = model.transcribe(audio_file)`

**Comment by bl4ckwind** [comment]
```
diarize_model = whisperx.DiarizationPipeline(
    use_auth_token="<YOUR_HF_TOKEN>", device=device
)
diarize_segments = diarize_model(whisperx.load_audio(audio_file_path), num_speakers=2)
result: DataFrame = whisperx.assign_word_speakers(diarize_segments, result)
```

**Comment by Scronkfink** [comment]
You can also make it into a shell command and run that instead.
