### ISSUE TITLE
Version 3.1.5 is distributed on pypi but Github repo only has 3.1.1?

### ISSUE THREAD

**Issue by dannguyen** [m-bain/whisperX#859]
(just more of an FYI)

Was hoping to use the latest version but bump up some of the requirement versions (e.g. faster-whisper), but looks like the [3.1.5 release](https://pypi.org/project/whisperx/3.1.5/) isn't yet part of the main github repo.

**Comment by OhsawaSenpai** [comment]
Sorry for the dumb question, but how then can I get the latest version?

Following the docs it states to do `pip install git+https://github.com/m-bain/whisperx.git` to install or `pip install git+https://github.com/m-bain/whisperx.git --upgrade` to update, but it seems this fetches the 3.1.1 version.

If I want the 3.1.5 version that exists in PyPI, what should I do?

**Comment by HHousen** [comment]
The pypi maintainer is not the creator of this repository: https://github.com/m-bain/whisperX/issues/722#issuecomment-2017297291.
