### ISSUE TITLE
Synchronizing plain text with a video using WhisperX

### ISSUE THREAD

**Issue by ext666** [m-bain/whisperX#86]
Hi, is it possible to use WhisperX (or any another tool) to synchronize a pre-made transcript with a video, i.e. skip the speech transcript phase and go straight to the timing phase?

It would help me a lot with creating subtitle templates, for which I get a transcript only.

Thanks a lot!

**Comment by dansommer** [comment]
I believe this was asked in a different way here...
https://github.com/m-bain/whisperX/issues/36

**Comment by ext666** [comment]
[dansommer](https://github.com/dansommer)
Thank you. If anybody else was interested, I also found this solution which works pretty well.
https://github.com/EtienneAb3d/WhisperTimeSync

**Comment by dansommer** [comment]
@ext666 Cool! Thanks for sharing that. Whisper is changing everything! 

There's also this classic list. https://github.com/pettarin/forced-alignment-tools

Aeneas is really good and fast for things like audio books with clear audio and a transcript that matches exactly what is in the audio. It supports 30 (?) languages. It doesn't handle clean verbatim transcripts so well with speaker disfluencies (um, hmm, errr, you know, like) removed from the transcript. 

Gentle is very good with English, clean verbatim transcripts, and less than great audio. It takes more computing power and time, but the output is very good. Gentle first runs auto-transcription on the audio and has timings down to the phoneme level, then matches the auto-transcript to the user-provided transcript and updates accordingly. Unfortunately, no automatic SRT output (that I'm aware of).
