### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by DaniruKun** [m-bain/whisperX#89]
The way that the CLI is implemented currently, it is unusable on a medium-size model and e.g. an hour or two long audio file.
The main problem is that after the transcription, the Whisper model is not properly GCed, and the cache isn't cleared, so there is just not enough memory for both the Whisper and the alignment model.
This is a huge issue since many people have consumer RTX 3000-series cards with only 6GB VRAM.

A quick solution is to not load all models at the same time, and properly GC the whisper model before doing the next steps:
```python
del whisper_model
gc.collect()
torch.cuda.empty_cache()
```

**Comment by m-bain** [comment]
i'll make model flushing an option soon, for cheaper gpu reqs. as well as using faster-whisper (but no ETA yet) as a drop-in replacement for whisper

**Comment by m-bain** [comment]
faster-whisper backend, and model flushing now in v3 version
should reduce gpu mem reqs a lot.
See https://github.com/m-bain/whisperX/issues/159#issuecomment-1521720723 for other ways to reduce gpu mem
