### ISSUE TITLE
Whisper large V3 turbo support?

### ISSUE THREAD

**Issue by utility-aagrawal** [m-bain/whisperX#898]
Does whisperx support the new large-V3 turbo model?

**Comment by Nyralei** [comment]
You can try. It supports any model for faster-whisper (https://github.com/SYSTRAN/faster-whisper)
This repo of WhisperX doesn't have the last version though. You can try my fork: https://github.com/Nyralei/whisperX
Also I have OpenAI API compatible API server, which uses this fork: https://github.com/Nyralei/whisperx-api-server

**Comment by heartInsert** [comment]
@Nyralei  Hi  mate ,  do your  fork  support  the  newest  turbo model ?

**Comment by Nyralei** [comment]
> @heartInsert
Yes, it does support any model for faster-whisper (meaning models with CTranslate2 format).
For turbo you can use this model - https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2

Calling it with (it will download model from huggingface automatically and put in HF_HOME directory):
```
whisperx --model "deepdml/faster-whisper-large-v3-turbo-ct2" ./123.wav
```

**Comment by eusoubrasileiro** [comment]
@Nyralei  thanks for reviving this project. Thanks a lot! Just wondering I still get errors like from your fork 

```>>Performing voice activity detection using Pyannote...
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../home/andre/.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.5.1+cu124. Bad things might happen unless you revert torch to 1.x.
```

**Comment by Nyralei** [comment]
> @Nyralei thanks for reviving this project. Thanks a lot! Just wondering I still get errors like from your fork
> 
> ```
> Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../home/andre/.cache/torch/whisperx-vad-segmentation.bin`
> Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
> Model was trained with torch 1.10.0+cu102, yours is 2.5.1+cu124. Bad things might happen unless you revert torch to 1.x.
> ```

This is just a warning. Should work without doing anything, but I think at some point this model (https://github.com/m-bain/whisperX/blob/main/whisperx/vad.py#L18) should be updated with new versions of libs.
