### ISSUE TITLE
whisperX not working with Google Collab? 

### ISSUE THREAD

**Issue by m01ali** [m-bain/whisperX#905]
![image](https://github.com/user-attachments/assets/d9b7e4dd-bc3c-48b1-be6f-8b295864fa30)
![image](https://github.com/user-attachments/assets/45b9ce30-cad8-4c04-bdfd-6b231bd2ac24)

**Comment by yangguang01** [comment]
Experiencing the same CUDA/cuDNN loading issue on Google Colab. When running whisperx, it shows the CUDA error message but produces no output files (no .txt or .srt generated). 
It was working fine before, but suddenly encountered this issue today.
As a workaround, adding `--device cpu --compute_type float32` parameters works fine, though slower.

**Comment by federicotorrielli** [comment]
see https://github.com/m-bain/whisperX/issues/901

**Comment by Barabazs** [comment]
This should be resolved with the latest release [v3.2.0](https://github.com/m-bain/whisperX/releases/tag/v3.2.0)
