### ISSUE TITLE
Phoneme-Based ASR For Arabic

### ISSUE THREAD

**Issue by MustaphaLargou25** [m-bain/whisperX#907]
Hi 😄 
I get a funetuned Wav2Vec 2.0 model for recognize arabic.
So this is a good addition for your project to support arabic.
This is the model on hunggingface hub:
https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-arabic

**Comment by Barabazs** [comment]
We're already using this model since 1b08661e42acb8a9210cabdcdc3afa3889f7aa9a
