### ISSUE TITLE
TranscriptionOptions.__new__() missing 1 required positional argument: 'hotwords'

### ISSUE THREAD

**Issue by Tejes** [m-bain/whisperX#918]
Since updating to WhisperX 3.1.6, I get the following error:

```
Traceback (most recent call last):
[...]
  File "/app/transcribe/models.py", line 168, in init_model
    self.model = whisperx.load_model(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/whisperx/asr.py", line 335, in load_model
    default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TranscriptionOptions.__new__() missing 1 required positional argument: 'hotwords'
```

Looks like this should be fixed by #904 . Staying at 3.1.5 in the meantime.

**Comment by pramadikaegamo** [comment]
If you want to keep running it with the latest version without having to wait for improvements to the WhisperX repository, you can use the following method:

asr_options = {
    "hotwords":None
}
# 1. Transcribe with original whisper (batched)
model = whisperx.load_model("large-v2", device, compute_type=compute_type, asr_options=asr_options)

**Comment by Manamama** [comment]
A very good tip. I had to wipe my Prooted Debian on Termux, and thus inadvertently upgraded all thereby. The whisperx based scripts then stopped working. 
BTW, version 3.1.5 installs different versions of other python modules than the 3.16 (and probably later ones) do, so one may try that older one if it may work on your non-standard *nix. (The most recent whisperx versions unexpectedly run also on barebones Termux, without any proot, now - while before it always ended in segmentation fault.)
