### ISSUE TITLE
Are these warning about torch version or pyannote version important?

### ISSUE THREAD

**Issue by ywangwxd** [m-bain/whisperX#933]
When I run the test, there were two warning messages:

> Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.5.1. Bad things might happen unless you revert torch to 1.x.

Can I ignore them?

**Comment by Barabazs** [comment]
You can ignore the warnings. See https://github.com/m-bain/whisperX/issues/546#issuecomment-1792848345 for more info.
