### ISSUE TITLE
VAD_SEGMENTATION_URL    has    Expired  

### ISSUE THREAD

**Issue by heartInsert** [m-bain/whisperX#943]
Today, when I tried to download the VAD model, I encountered an error: <HTTPError 403: 'Forbidden'>. After debugging, I found that the VAD_SEGMENTATION_URL is completely invalid. Could someone kindly fix this? Thank you for your reply.

**Comment by daho-jung-ringle** [comment]
Me either. 

Seems like below model is not accessible now

https://whisperx.s3.eu-west-2.amazonaws.com/model_weights/segmentation/0b5b3216d60a2d32fc086b47ea8c67589aaeb26b7e07fcbe620d6d0b83e209ea/pytorch_model.bin

**Comment by heartInsert** [comment]
Yes  , this url   in  amazonaws  has  corrupt  .

**Comment by daho-jung-ringle** [comment]
@heartInsert do you have any alternatives for this issue?

**Comment by maxchehab** [comment]
Started receiving this error at 10:02 PM EST.

**Comment by m-bain** [comment]
Yeah I had to stop it because some you guys spamming the s3 bucket (20k requests per day?), and the bill was running up like $1k a month, and my AWS credits expired...

**Comment by m-bain** [comment]
ill try host it on HF or sth

**Comment by heartInsert** [comment]
I  watch  the  size of   whisperx-vad-segmentation.bin   ,  it just   16.8MB  ,  maybe  we can    store  this  model   in  this  github  repository directly .

**Comment by m-bain** [comment]
can you test this:
https://github.com/m-bain/whisperX/pull/944

**Comment by m-bain** [comment]
dont have device with env right now

**Comment by heartInsert** [comment]
Yes  ,  I  have  tested it  and  it is  useful  in  my  device.

**Comment by m-bain** [comment]
what you mean useful 🤣, or you mean it works

**Comment by heartInsert** [comment]
It  works.

**Comment by daho-jung-ringle** [comment]
Seems like model path is not found in my device..

`
  File "/Users/dho/Library/Caches/pypoetry/virtualenvs/transcribe-KxoB4lOX-py3.11/lib/python3.11/site-packages/whisperx/vad.py", line 36, in load_vad_model
    raise FileNotFoundError(f"Model file not found at {model_fp}")
FileNotFoundError: Model file not found at /Users/dho/Library/Caches/pypoetry/virtualenvs/transcribe-KxoB4lOX-py3.11/lib/python3.11/site-packages/models/pytorch_model.bin
`

**Comment by daho-jung-ringle** [comment]
@m-bain Assume models folder should be included in the whisperx dir

Using - https://github.com/m-bain/whisperX/archive/161ae1f7ad2573444022f6231b715a3423664bc8.zip

**Comment by m-bain** [comment]
oh yeah good point, pip will only take the whisperx dir

**Comment by m-bain** [comment]
ok try now

**Comment by daho-jung-ringle** [comment]
@m-bain Thx! it works well :)
