### ISSUE TITLE
HFValidationError( huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'pyannote\segmentation'

### ISSUE THREAD

**Issue by rbychn** [m-bain/whisperX#95]
I'm trying to diarize but this error shows up, does anyone know what's causing this and how to fix it?

`(whisperx) C:\Users\Administrator\Desktop\...> whisperX audio_only.mp3 --diarize --hf_token <X> --min_speakers 2 --vad_filter --parallel_bs 32`

```
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\whisperx\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
  File "c:\users\administrator\desktop\whisperx\whisperx\transcribe.py", line 648, in cli
    vad_pipeline = Inference("pyannote/segmentation",
  File "C:\Users\Administrator\anaconda3\envs\whisperx\lib\site-packages\pyannote\audio\core\inference.py", line 99, in __init__
    else Model.from_pretrained(
  File "C:\Users\Administrator\anaconda3\envs\whisperx\lib\site-packages\pyannote\audio\core\model.py", line 786, in from_pretrained
    path_for_pl = hf_hub_download(
  File "C:\Users\Administrator\anaconda3\envs\whisperx\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\Administrator\anaconda3\envs\whisperx\lib\site-packages\huggingface_hub\utils\_validators.py", line 172, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'pyannote\segmentation'.
```

**Comment by rbychn** [comment]
only seems to be affected by --vad_filter

**Comment by willproctor** [comment]
this is a bug with pyannote and can be temporarily fixed on windows by modifying pyannote\audio\core\inference.py 

line 100

from:
        self.model = (
            model
            if isinstance(model, Model)
            else Model.from_pretrained(
                Path(model),
                map_location=device,
                strict=False,
                use_auth_token=use_auth_token,
            )
        )

to:
        self.model = (
            model
            if isinstance(model, Model)
            else Model.from_pretrained(
                model,
                map_location=device,
                strict=False,
                use_auth_token=use_auth_token,
            )
        )

**Comment by willproctor** [comment]
Raised a PR: https://github.com/pyannote/pyannote-audio/pull/1270

**Comment by rbychn** [comment]
That worked, thank you so much @willproctor!

**Comment by galaris** [comment]
> this is a bug with pyannote and can be temporarily fixed on windows by modifying pyannote\audio\core\inference.py
> 
> line 100
> 
> from: self.model = ( model if isinstance(model, Model) else Model.from_pretrained( Path(model), map_location=device, strict=False, use_auth_token=use_auth_token, ) )
> 
> to: self.model = ( model if isinstance(model, Model) else Model.from_pretrained( model, map_location=device, strict=False, use_auth_token=use_auth_token, ) )

Interesting, I already have your recommended line in the file (I guess it was already comitted because I did not change it), but I still have the same issue.

**Comment by m-bain** [comment]
VAD filter now downloads model from locally to torch cache I think this should not be an issue anymore, feel free to re-open
