### ISSUE TITLE
Failed to align segment (" 15.09.2021"): no characters in this segment found in model dictionary, resorting to original...

### ISSUE THREAD

**Issue by Oheed911** [m-bain/whisperX#98]
I am aligning the Whisper transcription and it gave me the above error, 15.09.2021 and the `{
            "id": 3,
            "seek": 3452,
            "start": 34.52,
            "end": 52.52,
            "text": " 15.09.2021",
            "tokens": [
                2119,
                13,
                13811,
                13,
                35016
            ],
            "temperature": 0.0,
            "avg_logprob": -0.934147940741645,
            "compression_ratio": 0.5555555555555556,
            "no_speech_prob": 1.6187204892048612e-05
        },`  it gives me failed to align. I dont know the reason why it is doing this?

**Comment by MrEnigmamgine** [comment]
I'm not involved in the project but I think I can answer this.  This warning is just telling you that it couldn't align the text "15.09.2021".  That's because the alignment model doesn't have a phenome dictionary for numbers and this text is comprised entirely of numbers.  If instead the text was "fifteen nine twenty twenty-one" you wouldn't receive this warning.

My understanding is that this is just a warning though, the results of the alignment should still be pretty good.

**Comment by Oheed911** [comment]
It gives me this error, "Failed to align segment: no characters in this segment found in model dictionary, resorting to original..."
and does not align the whole file and stops right there.

**Comment by matth** [comment]
Hello, can you share an example audio file with this error? I face the same issue on some files and am looking into a fix.

**Comment by Infinitay** [comment]
I came across this issue once but I no longer have the audio clip. I'll try and find an example, or if I come across it by chance again I'll share it here

**Comment by Infinitay** [comment]
Had it occur again when transcribing my audio files primarily working with the Korean language. One of many examples where this happens, the shortest audio clip I tested it again is 12 minutes long and I'll list that first. The command is the same for all of them, with the last argument being the path to the audio file.

whisperx Command: `whisperx --model medium --hf_token xxxx --vad_filter --parallel_bs 2 --language Korean --align_model wav2vec2-xls-r-300m-korean --output_dir "testing\` feel free to change the batch size of course to speed things up

Model: [wav2vec2-xls-r-300m-korean](https://huggingface.co/w11wo/wav2vec2-xls-r-300m-korean)

<table>
<tr>
	<td> #
	<td>Link
	<td>Duration (hh:ss:mm)
<tr>
	<td>1
	<td>https://www.youtube.com/watch?v=WBdQnhwO4gQ
	<td>00:12:30
<tr>
	<td>2
	<td>https://www.youtube.com/watch?v=dA9bYixDhBQ
	<td>01:00:00
</table>

Among the files I tested, these two were the audio clips that ran with no issue aside from the "failed to align segment... resorting to original..." warning with using VAD. The others resulted either in an `AssertionError` with "segments_list is empty" or "non-negative timestamp expected", or `IndexError` stating "list index out of range".

Oh and also `yt-dlp <link> --extract-audio --audio-format mp3 -o <save_as>.mp3`

**Comment by Oheed911** [comment]
hey @Infinitay, yes if I run my file with command line and provide vad_filter then it works, do you know how to implement it within python?

**Comment by mshakirDr** [comment]
I am using English with default settings in Colab. The batched version crashes with some of my files. Now that I run it with a batch argument, I get this error:
`Failed to align segment (""): no characters in this segment found in model dictionary, resorting to original...`
So I am not using the batch mode to save Colab credits on failed attempts. It takes more time but...

**Comment by m-bain** [comment]
num2word can work but unfortunately its a many-to-one mapping, see: https://github.com/m-bain/whisperX/issues/38#issuecomment-1497772886

Closing this for now as I think this failure shouldn't happen with recent patches v2/v3

**Comment by pragmaware** [comment]
I experience this problem with the latest v3.

```
Failed to align segment (" ..."): no characters in this segment found in model dictionary, resorting to original...
Traceback (most recent call last):
  File "/home/pragma/.pyenv/bin/whisperx", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/src/mentor/whisperX/whisperx/transcribe.py", line 178, in cli
    result = align(result["segments"], align_model, align_metadata, input_audio, device, interpolate_method=interpolate_method)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/src/mentor/whisperX/whisperx/alignment.py", line 319, in align
    char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pragma/.pyenv/lib/python3.11/site-packages/pandas/core/frame.py", line 6219, in reset_index
    new_obj.insert(
  File "/home/pragma/.pyenv/lib/python3.11/site-packages/pandas/core/frame.py", line 4782, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert subsegment-idx, already exists
```

It seems to happen when there is really no speech in one of the files to process, or the speech contains only numbers (like dates, mentioned before). 

I can fix my case by adding a fake row to char_segments_arr if the contents are empty, but this is likely naive and does not preserve the original unaligned contents (the numbers).
